local S = dofile("Test/support.lua")

-- FlightResolver depends on FlightGraph at runtime (LegTime/SumLegs call ns.FlightGraph.Get),
-- so load both. Returns (resolver, flightgraph).
local function fr()
    local ns = S.newNs()
    S.load(ns, "Lib/FlightGraph.lua")
    S.load(ns, "Lib/FlightResolver.lua")
    return ns._captured["FlightResolver"], ns._captured["FlightGraph"]
end

local function rec(seq, t, q) return { seq = seq, t = t, q = q or 2 } end

describe("FlightResolver.Quality", function()
    it("DIRECT outranks FLY and the values are the persisted 2/1", function()
        local r = fr()
        assert.are.equal(2, r.Quality().DIRECT)
        assert.are.equal(1, r.Quality().FLY)
        assert.is_true(r.Quality().DIRECT > r.Quality().FLY)
    end)
end)

describe("FlightResolver:LegTime (6-tier priority)", function()
    it("1: direct same-direction", function()
        local r, g = fr()
        local legs = g.Solve({ rec({ "A", "B" }, 10, 2) })
        assert.are.equal(10, r:LegTime(legs, "A", "B"))
    end)
    it("2: direct reverse-direction when no forward leg", function()
        local r, g = fr()
        local legs = g.Solve({ rec({ "B", "A" }, 20, 2) })
        assert.are.equal(20, r:LegTime(legs, "A", "B"))
    end)
    it("3: fly same-direction", function()
        local r, g = fr()
        local legs = g.Solve({ rec({ "A", "B" }, 15, 1) })
        assert.are.equal(15, r:LegTime(legs, "A", "B"))
    end)
    it("4: fly reverse-direction", function()
        local r, g = fr()
        local legs = g.Solve({ rec({ "B", "A" }, 25, 1) })
        assert.are.equal(25, r:LegTime(legs, "A", "B"))
    end)
    it("5: derived same-direction (from a span by subtraction)", function()
        local r, g = fr()
        -- span A->C over {B} = 160, leg B->C = 60  =>  A->B derived = 100
        local legs = g.Solve({ rec({ "A", "B", "C" }, 160, 2), rec({ "B", "C" }, 60, 2) })
        assert.is_true(g.Get(legs, "A", "B").derived)
        assert.are.equal(100, r:LegTime(legs, "A", "B"))
    end)
    it("6: derived reverse-direction", function()
        local r, g = fr()
        -- span B->C over {A} = 160, leg A->C = 60  =>  B->A derived = 100; query A->B
        local legs = g.Solve({ rec({ "B", "A", "C" }, 160, 2), rec({ "A", "C" }, 60, 2) })
        assert.is_true(g.Get(legs, "B", "A").derived)
        assert.are.equal(100, r:LegTime(legs, "A", "B"))
    end)
    it("ranks a reverse DIRECT above a forward FLY (tier 2 before tier 3)", function()
        local r, g = fr()
        local legs = g.Solve({ rec({ "A", "B" }, 15, 1), rec({ "B", "A" }, 20, 2) })
        assert.are.equal(20, r:LegTime(legs, "A", "B"))   -- reverse direct wins
    end)
    it("returns nil for an entirely unknown leg", function()
        local r, g = fr()
        assert.is_nil(r:LegTime(g.Solve({}), "A", "B"))
    end)
end)

describe("FlightResolver:SumLegs (never-fabricate)", function()
    it("sums the atomic legs of a fully-known route", function()
        local r, g = fr()
        local legs = g.Solve({ rec({ "A", "B" }, 10, 2), rec({ "B", "C" }, 20, 2) })
        assert.are.equal(30, r:SumLegs(legs, { "A", "B", "C" }))
    end)
    it("returns nil when ANY leg on the path is unknown", function()
        local r, g = fr()
        local legs = g.Solve({ rec({ "A", "B" }, 10, 2) })   -- B->D never recorded
        assert.is_nil(r:SumLegs(legs, { "A", "B", "D" }))
    end)
    it("a single-node path has no legs -> 0", function()
        local r, g = fr()
        assert.are.equal(0, r:SumLegs(g.Solve({}), { "A" }))
    end)
end)

describe("FlightResolver:NodeName (master-name normalisation)", function()
    it("strips a trailing ', <zone>' suffix", function()
        local r = fr()
        assert.are.equal("Orgrimmar", r:NodeName("Orgrimmar, Durotar"))
    end)
    it("passes a name with no comma through unchanged", function()
        local r = fr()
        assert.are.equal("Orgrimmar", r:NodeName("Orgrimmar"))
    end)
    it("trims surrounding whitespace", function()
        local r = fr()
        assert.are.equal("Orgrimmar", r:NodeName("  Orgrimmar  "))
        -- and trims the master name even when a zone suffix is present
        assert.are.equal("Stormwind", r:NodeName("  Stormwind , Elwynn"))
    end)
    it("passes a non-string argument through unchanged (no error)", function()
        local r = fr()
        assert.is_nil(r:NodeName(nil))
        assert.are.equal(42, r:NodeName(42))
    end)
end)
