local S = dofile("Test/support.lua")

local function sp()
    local ns = S.newNs()
    S.load(ns, "Lib/SlashParse.lua")
    return ns._captured["SlashParse"]
end

describe("SlashParse:Split", function()
    it("splits the command word from the remainder", function()
        local cmd, arg = (sp()):Split("set foo bar")
        assert.are.equal("set", cmd)
        assert.are.equal("foo bar", arg)
    end)
    it("lower-cases the command and trims the remainder (input is pre-trimmed by the router)", function()
        local cmd, arg = (sp()):Split("DUMP   nameplate  ")
        assert.are.equal("dump", cmd)
        assert.are.equal("nameplate", arg)
    end)
    it("a bare command has an empty remainder", function()
        local cmd, arg = (sp()):Split("list")
        assert.are.equal("list", cmd)
        assert.are.equal("", arg)
    end)
    it("nil / empty input -> ('', '')", function()
        local cmd, arg = (sp()):Split(nil)
        assert.are.equal("", cmd)
        assert.are.equal("", arg)
    end)
end)

describe("SlashParse:Pair", function()
    it("splits a name from a value, keeping the value's inner spaces", function()
        local name, value = (sp()):Pair("cameraDistanceMaxZoomFactor 2.6")
        assert.are.equal("cameraDistanceMaxZoomFactor", name)
        assert.are.equal("2.6", value)
        local n2, v2 = (sp()):Pair("someText hello there world")
        assert.are.equal("someText", n2)
        assert.are.equal("hello there world", v2)
    end)
    it("returns nil when there isn't both a name and a value", function()
        local name, value = (sp()):Pair("onlyname")
        assert.is_nil(name)
        assert.is_nil(value)
        assert.is_nil((sp()):Pair(""))
    end)
end)
