local addonName, ns = ...

-- Lib/LoadingScreenData.lua
-- GENERATED by tools/gen_loadingscreens.mjs -- do not edit by hand; regenerate after a patch.
-- One entry per WORLD map instance id (Map.db2): its loading screen's texture fileDataID (ls,
-- absent when the map has no own screen) and its expansion id (exp). Resolved at runtime from a
-- zone's uiMapID via C_Map.GetWorldPosFromMapPos (see the Dashboard's zone catalog).
ns.MapLoadingScreen = {
    [0] = { ls = 1498773, exp = 0 }, -- Eastern Kingdoms
    [1] = { ls = 1498775, exp = 0 }, -- Kalimdor
    [30] = { ls = 131861, exp = 0 }, -- Alterac Valley
    [33] = { ls = 131869, exp = 0 }, -- Shadowfang Keep
    [34] = { ls = 131870, exp = 0 }, -- Stormwind Stockade
    [36] = { ls = 131833, exp = 0 }, -- Deadmines
    [43] = { ls = 131882, exp = 0 }, -- Wailing Caverns
    [47] = { ls = 131865, exp = 0 }, -- Razorfen Kraul
    [48] = { ls = 131823, exp = 0 }, -- Blackfathom Deeps
    [70] = { ls = 131876, exp = 0 }, -- Uldaman
    [90] = { ls = 131841, exp = 0 }, -- Gnomeregan
    [109] = { ls = 131872, exp = 0 }, -- Sunken Temple
    [129] = { ls = 131864, exp = 0 }, -- Razorfen Downs
    [169] = { exp = 0 }, -- Emerald Dream
    [189] = { ls = 131852, exp = 0 }, -- Scarlet Monastery of Old
    [209] = { ls = 131885, exp = 0 }, -- Zul'Farrak
    [229] = { ls = 131825, exp = 0 }, -- Lower Blackrock Spire
    [230] = { ls = 131824, exp = 0 }, -- Blackrock Depths
    [249] = { ls = 131863, exp = 0 }, -- Onyxia's Lair
    [269] = { ls = 131830, exp = 1 }, -- Opening of the Dark Portal
    [289] = { ls = 131868, exp = 0 }, -- Scholomance
    [309] = { ls = 131886, exp = 0 }, -- Ancient Zul'Gurub
    [329] = { ls = 131871, exp = 0 }, -- Stratholme
    [349] = { ls = 131850, exp = 0 }, -- Maraudon
    [369] = { ls = 131834, exp = 0 }, -- Deeprun Tram
    [389] = { ls = 131862, exp = 0 }, -- Ragefire Chasm
    [409] = { ls = 131851, exp = 0 }, -- Molten Core
    [429] = { ls = 131835, exp = 0 }, -- Dire Maul
    [449] = { ls = 131831, exp = 0 }, -- Alliance PVP Barracks
    [450] = { ls = 131843, exp = 0 }, -- Horde PVP Barracks
    [469] = { ls = 131827, exp = 0 }, -- Blackwing Lair
    [489] = { ls = 131883, exp = 0 }, -- Classic Warsong Gulch
    [509] = { ls = 131818, exp = 0 }, -- Ruins of Ahn'Qiraj
    [529] = { ls = 131820, exp = 0 }, -- Classic Arathi Basin
    [530] = { ls = 447135, exp = 1 }, -- Outland
    [531] = { ls = 131819, exp = 0 }, -- Ahn'Qiraj Temple
    [532] = { ls = 131849, exp = 1 }, -- Karazhan
    [533] = { ls = 131854, exp = 2 }, -- Naxxramas
    [534] = { ls = 131830, exp = 1 }, -- The Battle for Mount Hyjal
    [540] = { ls = 131844, exp = 1 }, -- Hellfire Citadel: The Shattered Halls
    [542] = { ls = 131844, exp = 1 }, -- Hellfire Citadel: The Blood Furnace
    [543] = { ls = 131844, exp = 1 }, -- Hellfire Citadel: Ramparts
    [544] = { ls = 131846, exp = 1 }, -- Magtheridon's Lair
    [545] = { ls = 131832, exp = 1 }, -- Coilfang: The Steamvault
    [546] = { ls = 131832, exp = 1 }, -- Coilfang: The Underbog
    [547] = { ls = 131832, exp = 1 }, -- Coilfang: The Slave Pens
    [548] = { ls = 131832, exp = 1 }, -- Coilfang: Serpentshrine Cavern
    [550] = { ls = 131875, exp = 1 }, -- Tempest Keep
    [552] = { ls = 131875, exp = 1 }, -- Tempest Keep: The Arcatraz
    [553] = { ls = 131875, exp = 1 }, -- Tempest Keep: The Botanica
    [554] = { ls = 131875, exp = 1 }, -- Tempest Keep: The Mechanar
    [555] = { ls = 131821, exp = 1 }, -- Auchindoun: Shadow Labyrinth
    [556] = { ls = 131821, exp = 1 }, -- Auchindoun: Sethekk Halls
    [557] = { ls = 131821, exp = 1 }, -- Auchindoun: Mana-Tombs
    [558] = { ls = 131821, exp = 1 }, -- Auchindoun: Auchenai Crypts
    [559] = { ls = 131853, exp = 0 }, -- Nagrand Arena (old)
    [560] = { ls = 131830, exp = 1 }, -- The Escape from Durnholde
    [562] = { ls = 131828, exp = 0 }, -- zzOldBlade's Edge Arena
    [564] = { ls = 131826, exp = 1 }, -- Black Temple
    [565] = { ls = 131842, exp = 1 }, -- Gruul's Lair
    [566] = { ls = 131855, exp = 0 }, -- Eye of the Storm
    [568] = { ls = 514758, exp = 3 }, -- Zul'Aman
    [571] = { ls = 447134, exp = 2 }, -- Northrend
    [572] = { ls = 131867, exp = 0 }, -- Ruins of Lordaeron
    [574] = { ls = 131880, exp = 2 }, -- Utgarde Keep
    [575] = { ls = 131881, exp = 2 }, -- Utgarde Pinnacle
    [576] = { ls = 131856, exp = 2 }, -- The Nexus
    [578] = { ls = 131857, exp = 2 }, -- The Oculus
    [580] = { ls = 131873, exp = 1 }, -- The Sunwell
    [582] = { exp = 0 }, -- Transport: Rut'theran to Auberdine
    [584] = { exp = 0 }, -- Transport: Menethil to Theramore
    [585] = { ls = 131874, exp = 1 }, -- Magisters' Terrace
    [586] = { exp = 0 }, -- Transport: Exodar to Auberdine
    [587] = { exp = 0 }, -- Transport: Feathermoon Ferry
    [588] = { exp = 0 }, -- Transport: Menethil to Auberdine
    [589] = { exp = 0 }, -- Transport: Orgrimmar to Grom'Gol
    [590] = { exp = 0 }, -- Transport: Grom'Gol to Undercity
    [591] = { exp = 0 }, -- Transport: Undercity to Orgrimmar
    [592] = { exp = 0 }, -- Transport: Borean Tundra Test
    [593] = { exp = 0 }, -- Transport: Booty Bay to Ratchet
    [594] = { exp = 2 }, -- Transport: Howling Fjord Sister Mercy (Q
    [595] = { ls = 131859, exp = 2 }, -- The Culling of Stratholme
    [596] = { exp = 2 }, -- Transport: Naglfar
    [599] = { ls = 131877, exp = 2 }, -- Halls of Stone
    [600] = { ls = 131836, exp = 2 }, -- Drak'Tharon Keep
    [601] = { ls = 131822, exp = 2 }, -- Azjol-Nerub
    [602] = { ls = 131878, exp = 2 }, -- Halls of Lightning
    [603] = { ls = 131879, exp = 2 }, -- Ulduar
    [604] = { ls = 236061, exp = 2 }, -- Gundrak
    [607] = { ls = 236063, exp = 0 }, -- Strand of the Ancients
    [608] = { ls = 236058, exp = 2 }, -- Violet Hold
    [609] = { ls = 236060, exp = 2 }, -- Ebon Hold
    [610] = { exp = 0 }, -- Transport: Tirisfal to Vengeance Landing
    [612] = { exp = 0 }, -- Transport: Menethil to Valgarde
    [613] = { exp = 0 }, -- Transport: Orgrimmar to Warsong Hold
    [614] = { exp = 0 }, -- Transport: Stormwind to Valiance Keep
    [615] = { ls = 236057, exp = 2 }, -- The Obsidian Sanctum
    [616] = { ls = 236062, exp = 2 }, -- The Eye of Eternity
    [617] = { ls = 236059, exp = 0 }, -- Dalaran Sewers
    [619] = { ls = 236056, exp = 2 }, -- Ahn'kahet: The Old Kingdom
    [620] = { exp = 2 }, -- Transport: Moa'ki to Unu'pe
    [621] = { exp = 2 }, -- Transport: Moa'ki to Kamagua
    [622] = { exp = 2 }, -- Transport: Orgrim's Hammer
    [623] = { exp = 2 }, -- Transport: The Skybreaker
    [624] = { ls = 236065, exp = 2 }, -- Vault of Archavon
    [627] = { ls = 131840, exp = 6 }, -- Unused (DELETE ME)
    [673] = { exp = 2 }, -- Transport: Orgrim's Hammer (Icecrown Cit
    [674] = { exp = 3 }, -- Transport: Ship to Vashj'ir
    [628] = { ls = 309885, exp = 2 }, -- Isle of Conquest
    [631] = { ls = 318964, exp = 2 }, -- Icecrown Citadel
    [632] = { ls = 317257, exp = 2 }, -- The Forge of Souls
    [637] = { ls = 131838, exp = 3 }, -- Abyssal Maw Exterior
    [638] = { ls = 1498773, exp = 0 }, -- Gilneas
    [641] = { exp = 2 }, -- Transport: Alliance Airship BG
    [642] = { exp = 2 }, -- Transport: HordeAirshipBG
    [643] = { ls = 397151, exp = 3 }, -- Throne of the Tides
    [644] = { ls = 400719, exp = 3 }, -- Halls of Origination
    [645] = { ls = 418218, exp = 3 }, -- Blackrock Caverns
    [646] = { ls = 424078, exp = 3 }, -- Deepholm
    [647] = { exp = 2 }, -- Transport: Orgrimmar to Thunder Bluff
    [648] = { ls = 1498775, exp = 0 }, -- LostIsles
    [649] = { ls = 310729, exp = 2 }, -- Trial of the Crusader
    [650] = { ls = 311102, exp = 2 }, -- Trial of the Champion
    [654] = { ls = 1498773, exp = 0 }, -- Gilneas2
    [655] = { exp = 0 }, -- GilneasPhase1
    [656] = { exp = 0 }, -- GilneasPhase2
    [657] = { ls = 402550, exp = 3 }, -- The Vortex Pinnacle
    [658] = { ls = 335909, exp = 2 }, -- Pit of Saron
    [659] = { ls = 1498775, exp = 0 }, -- Lost Isles Volcano Eruption
    [661] = { exp = 0 }, -- Lost Isles Town in a Box
    [662] = { exp = 3 }, -- Transport: Alliance Vashj'ir Ship
    [668] = { ls = 336388, exp = 2 }, -- Halls of Reflection
    [669] = { ls = 404445, exp = 3 }, -- Blackwing Descent
    [670] = { ls = 401943, exp = 3 }, -- Grim Batol
    [671] = { ls = 407545, exp = 3 }, -- The Bastion of Twilight
    [672] = { exp = 2 }, -- Transport: The Skybreaker (Icecrown Cita
    [712] = { exp = 2 }, -- Transport: The Skybreaker (IC Dungeon)
    [713] = { exp = 2 }, -- Transport: Orgrim's Hammer (IC Dungeon)
    [718] = { exp = 2 }, -- Transport: The Mighty Wind (Icecrown Cit
    [719] = { ls = 1498775, exp = 0 }, -- Mount Hyjal Phase 1
    [720] = { ls = 514270, exp = 3 }, -- Firelands
    [721] = { exp = 3 }, -- Firelands Terrain 2
    [723] = { exp = 0 }, -- Stormwind
    [724] = { ls = 365622, exp = 2 }, -- The Ruby Sanctum
    [725] = { ls = 401942, exp = 3 }, -- The Stonecore
    [726] = { ls = 407226, exp = 3 }, -- Twin Peaks
    [727] = { ls = 633155, exp = 4 }, -- Silvershard Mines
    [730] = { ls = 512032, exp = 3 }, -- Maelstrom Zone
    [731] = { ls = 1498775, exp = 0 }, -- Stonetalon Bomb
    [732] = { ls = 411683, exp = 3 }, -- Tol Barad
    [734] = { ls = 131818, exp = 2 }, -- Ahn'Qiraj Terrace
    [736] = { exp = 0 }, -- Twilight Highlands Dragonmaw Phase
    [738] = { exp = 3 }, -- Ship to Vashj'ir (Orgrimmar -> Vashj'ir)
    [739] = { exp = 3 }, -- Vashj'ir Sub - Horde
    [740] = { exp = 3 }, -- Vashj'ir Sub - Alliance
    [741] = { exp = 3 }, -- Twilight Highlands Horde Transport
    [742] = { exp = 3 }, -- Vashj'ir Sub - Horde - Circling Abyssal 
    [743] = { exp = 3 }, -- Vashj'ir Sub - Alliance circling Abyssal
    [746] = { exp = 0 }, -- Uldum Phase Oasis
    [747] = { exp = 3 }, -- Transport: Deepholm Gunship
    [748] = { exp = 3 }, -- Transport: Onyxia/Nefarian Elevator
    [749] = { exp = 0 }, -- Transport: Gilneas Moving Gunship
    [750] = { exp = 0 }, -- Transport: Gilneas Static Gunship
    [751] = { exp = 0 }, -- Redridge - Orc Bomb
    [752] = { exp = 0 }, -- Redridge - Bridge Phase One
    [753] = { exp = 0 }, -- Redridge - Bridge Phase Two
    [754] = { ls = 450109, exp = 3 }, -- Throne of the Four Winds
    [755] = { ls = 411684, exp = 3 }, -- Lost City of the Tol'vir
    [757] = { ls = 468402, exp = 3 }, -- Baradin Hold
    [759] = { exp = 0 }, -- Uldum Phased Entrance
    [760] = { exp = 0 }, -- Twilight Highlands Phased Entrance
    [761] = { ls = 427941, exp = 0 }, -- The Battle for Gilneas
    [762] = { exp = 3 }, -- Twilight Highlands Zeppelin 1
    [763] = { exp = 3 }, -- Twilight Highlands Zeppelin 2
    [764] = { exp = 0 }, -- Uldum - Phase Wrecked Camp
    [765] = { exp = 3 }, -- Krazzworks Attack Zeppelin
    [766] = { exp = 0 }, -- Transport: Gilneas Moving Gunship 02
    [767] = { exp = 0 }, -- Transport: Gilneas Moving Gunship 03
    [859] = { ls = 131886, exp = 3 }, -- Zul'Gurub
    [860] = { ls = 574578, exp = 0 }, -- The Wandering Isle
    [861] = { ls = 514085, exp = 3 }, -- Molten Front
    [870] = { ls = 651994, exp = 4 }, -- Pandaria
    [930] = { ls = 131840, exp = 6 }, -- A Dark Place
    [938] = { ls = 535280, exp = 3 }, -- End Time
    [939] = { ls = 535281, exp = 3 }, -- Well of Eternity
    [940] = { ls = 535413, exp = 3 }, -- Hour of Twilight
    [951] = { ls = 131857, exp = 3 }, -- Nexus Legendary
    [959] = { ls = 633153, exp = 4 }, -- Shado-Pan Monastery
    [960] = { ls = 633149, exp = 4 }, -- Temple of the Jade Serpent
    [961] = { ls = 633156, exp = 4 }, -- Stormstout Brewery
    [962] = { ls = 633147, exp = 4 }, -- Gate of the Setting Sun
    [967] = { ls = 534812, exp = 3 }, -- Dragon Soul
    [968] = { ls = 131855, exp = 0 }, -- Rated Eye of the Storm
    [971] = { exp = 4 }, -- Jade Forest Alliance Hub Phase
    [972] = { exp = 4 }, -- Jade Forest Battlefield Phase
    [974] = { ls = 2821800, exp = 0 }, -- Darkmoon Faire
    [975] = { ls = 574578, exp = 0 }, -- Turtle Ship Phase 01
    [976] = { ls = 574578, exp = 0 }, -- Turtle Ship Phase 02
    [977] = { exp = 3 }, -- Maelstrom Deathwing Fight
    [980] = { ls = 633157, exp = 3 }, -- Tol'Viron Arena
    [994] = { ls = 633150, exp = 4 }, -- Mogu'shan Palace
    [995] = { exp = 4 }, -- The Depths [UNUSED]
    [996] = { ls = 643909, exp = 4 }, -- Terrace of Endless Spring
    [998] = { ls = 633158, exp = 4 }, -- Temple of Kotmogu
    [999] = { ls = 650621, exp = 3 }, -- Theramore's Fall (H)
    [1000] = { ls = 651536, exp = 3 }, -- Theramore's Fall (A)
    [1001] = { ls = 643908, exp = 0 }, -- Scarlet Halls
    [1004] = { ls = 645156, exp = 0 }, -- Scarlet Monastery
    [1005] = { ls = 647838, exp = 4 }, -- A Brewing Storm
    [1007] = { ls = 633152, exp = 0 }, -- Scholomance
    [1008] = { ls = 633151, exp = 4 }, -- Mogu'shan Vaults
    [1009] = { ls = 633148, exp = 4 }, -- Heart of Fear
    [1011] = { ls = 633154, exp = 4 }, -- Siege of Niuzao Temple
    [1014] = { ls = 651994, exp = 6 }, -- Peak of Serenity
    [1019] = { ls = 1498775, exp = 4 }, -- Ruins of Theramore
    [1024] = { ls = 652549, exp = 4 }, -- Greenstone Village
    [1028] = { exp = 4 }, -- (UNUSED) Scenario: Mogu Ruins
    [1029] = { exp = 4 }, -- (UNUSED) Scenario: Mogu Crypt
    [1030] = { ls = 652548, exp = 4 }, -- Crypt of Forgotten Kings
    [1031] = { ls = 841556, exp = 4 }, -- Arena of Annihilation
    [1032] = { exp = 4 }, -- Pet Battle - Jade Forest
    [1035] = { ls = 795305, exp = 4 }, -- Temple of Kotmogu
    [1043] = { ls = 2821799, exp = 2 }, -- Brawl'gar Arena
    [1048] = { ls = 647839, exp = 4 }, -- Unga Ingoo
    [1049] = { ls = 131829, exp = 4 }, -- (UNUSED) Scenario: Black Ox Temple
    [1050] = { ls = 775634, exp = 4 }, -- Assault on Zan'vess
    [1051] = { ls = 652547, exp = 4 }, -- Brewmoon Festival
    [1061] = { exp = 4 }, -- Horde Beach Daily Area
    [1062] = { exp = 4 }, -- Alliance Beach Daily Area
    [1064] = { ls = 804100, exp = 4 }, -- Mogu Island Daily Area
    [1066] = { exp = 0 }, -- Stormwind Gunship Pandaria Start Area
    [1074] = { exp = 0 }, -- Orgrimmar Gunship Pandaria Start
    [1075] = { exp = 0 }, -- Theramore's Fall Phase
    [1076] = { exp = 4 }, -- Jade Forest Horde Starting Area
    [1095] = { ls = 774866, exp = 4 }, -- Dagger in the Dark
    [1098] = { ls = 801471, exp = 4 }, -- Throne of Thunder
    [1099] = { ls = 852904, exp = 4 }, -- Naval Battle Scenario
    [1101] = { exp = 4 }, -- Defense Of The Ale House BG
    [1102] = { ls = 774864, exp = 4 }, -- Domination Point
    [1103] = { ls = 774865, exp = 4 }, -- Lion's Landing
    [1104] = { ls = 775426, exp = 4 }, -- A Little Patience
    [1105] = { ls = 875627, exp = 4 }, -- Deepwind Gorge (Legacy)
    [1106] = { ls = 236058, exp = 4 }, -- Jaina Dalaran Scenario
    [1107] = { ls = 1394926, exp = 6 }, -- Dreadscar Rift
    [1112] = { ls = 131826, exp = 4 }, -- Pursuing the Black Harvest
    [1113] = { exp = 0 }, -- Transport: DarkmoonCarousel
    [1116] = { ls = 1035009, exp = 5 }, -- Draenor
    [1120] = { exp = 4 }, -- Thunder King Horde Hub
    [1121] = { exp = 4 }, -- Thunder Island Alliance Hub
    [1122] = { exp = 4 }, -- City Siege - Mogu Island Progression Sce
    [1123] = { exp = 4 }, -- Lightning Forge - Mogu Island Progressio
    [1124] = { exp = 4 }, -- Shipyard - Mogu Island Progression Scena
    [1125] = { exp = 4 }, -- Alliance Hub - Mogu Island Progression S
    [1126] = { ls = 804100, exp = 4 }, -- Mogu Island Progression Events
    [1127] = { exp = 4 }, -- Final Gate - Mogu Island Progression Sce
    [1128] = { exp = 4 }, -- Mogu Island Events - Horde Base
    [1129] = { exp = 4 }, -- Mogu Island Events - Alliance Base
    [1130] = { ls = 853210, exp = 4 }, -- Blood in the Snow
    [1131] = { ls = 852903, exp = 4 }, -- The Secrets of Ragefire
    [1132] = { exp = 0 }, -- Transport: The Skybag (Brawl'gar Arena)
    [1133] = { exp = 0 }, -- Transport: Zandalari Ship (Mogu Island)
    [1134] = { ls = 851882, exp = 4 }, -- The Tiger's Peak
    [1135] = { ls = 801471, exp = 4 }, -- Mogu Island Loot Room
    [1136] = { ls = 903869, exp = 4 }, -- Siege of Orgrimmar
    [1144] = { ls = 874615, exp = 4 }, -- Heart of the Old God Scenario
    [1148] = { ls = 841556, exp = 4 }, -- Proving Grounds
    [1152] = { ls = 1086951, exp = 5 }, -- FW Horde Garrison Level 1
    [1153] = { ls = 1086951, exp = 5 }, -- FW Horde Garrison Level 3
    [1154] = { ls = 1086951, exp = 5 }, -- FW Horde Garrison Level 4
    [1155] = { exp = 4 }, -- Stromgarde Keep
    [1157] = { ls = 651994, exp = 4 }, -- Halfhill Scenario
    [1158] = { ls = 1099378, exp = 5 }, -- SMV Alliance Garrison Level 1
    [1159] = { ls = 1099378, exp = 5 }, -- SMV Alliance Garrison Level 3
    [1160] = { ls = 1099378, exp = 5 }, -- SMV Alliance Garrison Level 4
    [1161] = { ls = 651994, exp = 4 }, -- Celestial Tournament
    [1168] = { exp = 5 }, -- The Purge Of Grommar - Scenario
    [1170] = { ls = 851882, exp = 6 }, -- Shado-Pan Showdown
    [1172] = { exp = 0 }, -- Transport: Siege of Orgrimmar (Alliance)
    [1173] = { exp = 0 }, -- Transport: Siege of Orgrimmar (Horde)
    [1175] = { ls = 1013075, exp = 5 }, -- Bloodmaul Slag Mines
    [1176] = { ls = 1033059, exp = 5 }, -- Shadowmoon Burial Grounds
    [1179] = { ls = 1498775, exp = 5 }, -- Warcraft Heroes
    [1181] = { exp = 0 }, -- PattyMack Test Garrison Bldg Map
    [1182] = { ls = 1034725, exp = 5 }, -- Auchindoun
    [1187] = { exp = 5 }, -- GOR Alliance Garrison Level 1
    [1188] = { exp = 5 }, -- GOR Alliance Garrison Level 2
    [1189] = { exp = 5 }, -- GOR Alliance Garrison Level 3
    [1190] = { ls = 1498773, exp = 4 }, -- Blasted Lands Phase
    [1191] = { ls = 1035009, exp = 5 }, -- Ashran
    [1192] = { exp = 5 }, -- Transport: Gorgrond Train
    [1195] = { ls = 1058991, exp = 5 }, -- Iron Docks
    [1200] = { exp = 5 }, -- Bonetown Scenario
    [1203] = { ls = 1035009, exp = 5 }, -- Frostfire Finale Scenario
    [1205] = { ls = 1032622, exp = 5 }, -- Blackrock Foundry
    [1207] = { ls = 1035009, exp = 5 }, -- The Battle for Shattrath
    [1208] = { ls = 1017727, exp = 5 }, -- Grimrail Depot
    [1209] = { ls = 1033900, exp = 5 }, -- Skyreach
    [1212] = { exp = 5 }, -- Garrison - Alliance - Blacksmith 3
    [1213] = { exp = 5 }, -- Garrison - Alliance - Alchemy 1
    [1214] = { exp = 5 }, -- Garrison - Alliance - Enchanting 3
    [1215] = { exp = 5 }, -- Garrison - Alliance - Engineering 3
    [1216] = { exp = 5 }, -- Garrison - Alliance - Farm1
    [1217] = { exp = 5 }, -- Garrison - Alliance - Inscription 1
    [1218] = { exp = 5 }, -- Garrison - Alliance - Jewelcrafting 1
    [1219] = { exp = 5 }, -- Garrison - Alliance - Leatherworking 1
    [1220] = { ls = 1446595, exp = 6 }, -- Broken Isles
    [1221] = { exp = 5 }, -- Garrison - Alliance Mine 1
    [1222] = { exp = 5 }, -- Garrison - Alliance Mine 2
    [1223] = { exp = 5 }, -- Garrison - Alliance Mine 3
    [1224] = { exp = 5 }, -- Garrison - Alliance Stable 1
    [1225] = { exp = 5 }, -- Garrison - Alliance Stable 2
    [1226] = { exp = 5 }, -- Garrison - Alliance Stable 3
    [1227] = { exp = 5 }, -- Garrison - Alliance - Tailoring 3
    [1228] = { ls = 1033498, exp = 5 }, -- Highmaul
    [1229] = { exp = 5 }, -- Garrison - Alliance - Inn 1
    [1230] = { exp = 5 }, -- Garrison - Alliance - Barn 1
    [1231] = { exp = 5 }, -- Transport: Wavemurder Barge
    [1232] = { exp = 5 }, -- GOR Horde Garrison Level 0
    [1233] = { exp = 5 }, -- GOR Horde Garrison Level 3
    [1234] = { exp = 5 }, -- TAL Alliance Garrison Level 0
    [1235] = { exp = 5 }, -- TAL Alliance Garrison Level 3
    [1236] = { exp = 5 }, -- TAL Horde Garrison Level 0
    [1237] = { exp = 5 }, -- TAL Horde Garrison Level 3
    [1238] = { exp = 5 }, -- SOA Alliance Garrison Level 0
    [1239] = { exp = 5 }, -- SOA Alliance Garrison Level 3
    [1240] = { exp = 5 }, -- SOA Horde Garrison Level 0
    [1241] = { exp = 5 }, -- SOA Horde Garrison Level 3
    [1242] = { exp = 5 }, -- NAG Alliance Garrison Level 0
    [1243] = { exp = 5 }, -- NAG Alliance Garrison Level 3
    [1244] = { exp = 5 }, -- NAG Horde Garrison Level 0
    [1245] = { exp = 5 }, -- NAG Horde Garrison Level 3
    [1247] = { exp = 5 }, -- Garrison - Alliance - Armory 1
    [1248] = { exp = 5 }, -- Garrison - Alliance - Barracks 1
    [1249] = { exp = 5 }, -- Garrison - Alliance - Engineering 1
    [1250] = { exp = 5 }, -- Alliance - Garrison - Herb Garden 1 (UNU
    [1251] = { exp = 5 }, -- Alliance - Garrison - Inn 1 DONT USE
    [1252] = { exp = 5 }, -- Garrison - Alliance - Lumbermill 1
    [1253] = { exp = 5 }, -- Garrison - Alliance - Mage Tower 1
    [1254] = { exp = 5 }, -- Garrison - Alliance - Sparring Arena 1
    [1255] = { exp = 5 }, -- Garrison - Alliance - Salvage Yard 1
    [1256] = { exp = 5 }, -- Garrison - Alliance - StoreHouse 1
    [1257] = { exp = 5 }, -- Garrison - Alliance - Trading Post 1
    [1258] = { exp = 5 }, -- Garrison - Alliance - Tailoring 1
    [1259] = { exp = 5 }, -- Garrison - Alliance - Enchanting 1
    [1260] = { exp = 5 }, -- Garrison - Alliance - Blacksmith 1
    [1261] = { exp = 5 }, -- Garrison - Alliance - Plot Small
    [1262] = { exp = 5 }, -- Garrison - Allilance - Plot Medium
    [1263] = { exp = 5 }, -- Garrison - Alliance - Plot Large
    [1265] = { ls = 1035009, exp = 5 }, -- Tanaan Jungle Intro
    [1266] = { ls = 1035009, exp = 5 }, -- Circle of Blood Scenario
    [1268] = { ls = 1035009, exp = 5 }, -- Teron'gor's Confrontation
    [1273] = { exp = 5 }, -- Nagrand - Garrison Camp - Stable2
    [1277] = { ls = 1035009, exp = 5 }, -- Defense of Karabor
    [1278] = { exp = 5 }, -- Garrison - Horde - Barracks 1
    [1279] = { ls = 1060205, exp = 5 }, -- The Everbloom
    [1280] = { ls = 1498773, exp = 5 }, -- Southshore vs. Tarren Mill
    [1281] = { exp = 5 }, -- Garrison - Horde - Alchemy 1
    [1282] = { exp = 5 }, -- Garrison - Horde - Armory 1
    [1283] = { exp = 5 }, -- Garrison - Horde - Barn 1
    [1284] = { exp = 5 }, -- Garrison - Horde - Blacksmith 1
    [1285] = { exp = 5 }, -- Garrison - Horde - Enchanting 1
    [1286] = { exp = 5 }, -- Garrison - Horde - Engineering 1
    [1287] = { exp = 5 }, -- Garrison - Horde - Inn 1
    [1288] = { exp = 5 }, -- Garrison - Horde - Inscription 1
    [1453] = { ls = 1035009, exp = 6 }, -- Scourge of Northshire
    [1289] = { exp = 5 }, -- Garrison - Horde - Jewelcrafting 1
    [1290] = { exp = 5 }, -- Garrison - Horde - Leatherworking 1
    [1291] = { exp = 5 }, -- Garrison - Horde - Lumbermill 1
    [1292] = { exp = 5 }, -- Garrison - Horde - Mage Tower 1
    [1293] = { exp = 5 }, -- Garrison - Horde - Mine 1
    [1294] = { exp = 5 }, -- Garrison - Horde - Pet Stable 1
    [1295] = { exp = 5 }, -- Garrison - Horde - Salvage Yard 1
    [1296] = { exp = 5 }, -- Garrison - Horde - Sparring Arena 1
    [1297] = { exp = 5 }, -- Garrison - Horde - Stable 1
    [1298] = { exp = 5 }, -- Garrison - Horde Storehouse 1
    [1299] = { exp = 5 }, -- Garrison - Horde - Tailoring 1
    [1300] = { exp = 5 }, -- Garrison - Horde - Trading Post 1
    [1301] = { exp = 5 }, -- Garrison - Horde - Workshop 1
    [1302] = { exp = 5 }, -- Garrison - Alliance - Workshop 1
    [1303] = { exp = 5 }, -- Garrison - Horde - Farm1
    [1304] = { exp = 5 }, -- Garrison - Horde - Plot Large
    [1305] = { exp = 5 }, -- Garrison - Horde - Plot Medium
    [1306] = { exp = 5 }, -- Garrison - Horde - Plot Small
    [1307] = { exp = 5 }, -- Tanaan Jungle Intro - Forge Phase
    [1308] = { exp = 5 }, -- Garrison - Horde - Fishing 1
    [1309] = { exp = 5 }, -- Garrison - Alliance - Fishing 1
    [1311] = { exp = 5 }, -- Outdoor Garrison - Arena - Horde (NEEDS 
    [1312] = { exp = 5 }, -- Outdoor Garrison - Arena - Alliance (NEE
    [1313] = { exp = 5 }, -- Outdoor Garrison - Lumber Mill - Allianc
    [1314] = { exp = 5 }, -- Outdoor Garrison - Lumber Mill - Horde
    [1315] = { exp = 5 }, -- Outdoor Garrison - Armory - Horde
    [1316] = { exp = 5 }, -- Outdoor Garrison - Armory - Alliance
    [1317] = { exp = 5 }, -- Outdoor Garrison - Mage Tower - Horde
    [1318] = { exp = 5 }, -- Outdoor Garrison - Mage Tower - Alliance
    [1319] = { exp = 5 }, -- Outdoor Garrison - Stables - Horde
    [1320] = { exp = 5 }, -- Outdoor Garrison - Stables - Alliance
    [1321] = { exp = 5 }, -- Outdoor Garrison - Workshop - Horde
    [1322] = { exp = 5 }, -- Outdoor Garrison - Workshop - Alliance
    [1323] = { exp = 5 }, -- Outdoor Garrison - Inn - Horde
    [1324] = { exp = 5 }, -- Outdoor Garrison - Inn - Alliance
    [1325] = { exp = 5 }, -- Outdoor Garrison - Tradiing Post 1 - Hor
    [1326] = { exp = 5 }, -- Outdoor Garrison - Tradiing Post - Allia
    [1327] = { exp = 5 }, -- Outdoor Garrison - Construction Plot, Me
    [1328] = { exp = 5 }, -- Outdoor Garrison - Construction Plot, Me
    [1329] = { exp = 5 }, -- Grommashar Scenario
    [1330] = { ls = 1086951, exp = 5 }, -- FW Horde Garrison Level 2
    [1331] = { ls = 1099378, exp = 5 }, -- SMV Alliance Garrison Level 2
    [1332] = { exp = 5 }, -- Garrison - Horde - Barracks 2
    [1333] = { exp = 5 }, -- Garrison - Horde - Armory 2
    [1334] = { exp = 5 }, -- Garrison - Horde - Barn 2
    [1335] = { exp = 5 }, -- Garrison - Horde - Inn 2
    [1336] = { exp = 5 }, -- Garrison - Horde - Lumbermill 2
    [1337] = { exp = 5 }, -- Garrison - Horde - Mage Tower 2
    [1338] = { exp = 5 }, -- Garrison - Horde - Pet Stable 2
    [1339] = { exp = 5 }, -- Garrison - Horde - Stable 2
    [1340] = { exp = 5 }, -- Garrison - Horde - Trading Post 2
    [1341] = { exp = 5 }, -- Garrison - Horde - Workshop 2
    [1342] = { exp = 5 }, -- Garrison - Horde - Barracks 3
    [1343] = { exp = 5 }, -- Garrison - Horde - Armory 3
    [1344] = { exp = 5 }, -- Garrison - Horde - Barn 3
    [1345] = { exp = 5 }, -- Garrison - Horde - Inn 3
    [1346] = { exp = 5 }, -- Garrison - Horde - Mage Tower 3
    [1347] = { exp = 5 }, -- Garrison - Horde - Pet Stable 3
    [1348] = { exp = 5 }, -- Garrison - Horde - Stable 3
    [1349] = { exp = 5 }, -- Garrison - Horde - Trading Post 3
    [1350] = { exp = 5 }, -- Garrison - Horde - Workshop 3
    [1351] = { exp = 5 }, -- Garrison - Alliance - Large - Constructi
    [1352] = { exp = 5 }, -- Garrison - Alliance - Medium - Construct
    [1353] = { exp = 5 }, -- Garrison - Horde - Large - Construction
    [1354] = { exp = 5 }, -- Garrison - Horde - Medium - Construction
    [1358] = { ls = 1035275, exp = 5 }, -- Upper Blackrock Spire
    [1361] = { exp = 5 }, -- Garrison - Alliance - Mage Tower 2
    [1362] = { exp = 5 }, -- Garrison - Alliance - Mage Tower 3
    [1363] = { exp = 5 }, -- Garrison - Horde - Mine 2
    [1364] = { exp = 5 }, -- Garrison - Horde - Mine 3
    [1367] = { exp = 5 }, -- Garrison - Alliance - Workshop 2
    [1368] = { exp = 5 }, -- Garrison - Alliance - Workshop 3
    [1369] = { exp = 5 }, -- Garrison - Alliance - Lumbermill 2
    [1370] = { exp = 5 }, -- Garrison - Alliance - Lumbermill 3
    [1371] = { exp = 5 }, -- Garrison - Horde - Small - Construction
    [1372] = { exp = 5 }, -- Garrison - Alliance - Small - Constructi
    [1374] = { ls = 1035009, exp = 5 }, -- Auchindoun Quest
    [1375] = { exp = 5 }, -- Garrison - Alliance - Alchemy 2
    [1376] = { exp = 5 }, -- Garrison - Alliance - Alchemy 3
    [1377] = { exp = 5 }, -- Garrison - Alliance - Blacksmith 2
    [1378] = { exp = 5 }, -- Garrison - Alliance - Enchanting 2
    [1379] = { exp = 5 }, -- Garrison - Alliance - Engineering 2
    [1380] = { exp = 5 }, -- Garrison - Alliance - Inscription 2
    [1381] = { exp = 5 }, -- Garrison - Alliance - Inscription 3
    [1382] = { exp = 5 }, -- Garrison - Alliance - Jewelcrafting 2
    [1383] = { exp = 5 }, -- Garrison - Alliance - Jewelcrafting 3
    [1384] = { exp = 5 }, -- Garrison - Alliance - Leatherworking 2
    [1385] = { exp = 5 }, -- Garrison - Alliance - Leatherworking 3
    [1386] = { exp = 5 }, -- Garrison - Alliance - Tailoring 2
    [1387] = { exp = 5 }, -- Garrison - Alliance - StoreHouse 2
    [1388] = { exp = 5 }, -- Garrison - Alliance - StoreHouse 3
    [1389] = { exp = 5 }, -- Garrison - Horde Storehouse 2
    [1390] = { exp = 5 }, -- Garrison - Horde Storehouse 3
    [1391] = { exp = 5 }, -- Garrison - Alliance - Salvage Yard 2
    [1392] = { exp = 5 }, -- Garrison - Alliance - Salvage Yard 3
    [1393] = { exp = 5 }, -- Garrison - Horde - Lumbermill 3
    [1394] = { exp = 5 }, -- Garrison - Alliance - Sparring Arena 2
    [1395] = { exp = 5 }, -- Garrison - Alliance - Sparring Arena 3
    [1396] = { exp = 5 }, -- Garrison - Alliance - Trading Post 2
    [1397] = { exp = 5 }, -- Garrison - Alliance - Trading Post 3
    [1398] = { exp = 5 }, -- Garrison - Alliance - Barn 2
    [1399] = { exp = 5 }, -- Garrison - Alliance - Barn 3
    [1400] = { exp = 5 }, -- Garrison - Alliance - Inn 2
    [1401] = { exp = 5 }, -- Garrison - Alliance - Inn 3
    [1402] = { ls = 1035009, exp = 5 }, -- Gorgrond Finale
    [1403] = { exp = 5 }, -- Garrison - Alliance - Barracks 2
    [1404] = { exp = 5 }, -- Garrison - Alliance - Barracks 3
    [1405] = { exp = 5 }, -- Garrison - Alliance - Armory 2
    [1406] = { exp = 5 }, -- Garrison - Alliance - Armory 3
    [1409] = { exp = 5 }, -- Garrison - Horde - Sparring Arena 2
    [1410] = { exp = 5 }, -- Garrison - Horde - Sparring Arena 3
    [1411] = { exp = 5 }, -- Garrison - Horde - Alchemy 2
    [1412] = { exp = 5 }, -- Garrison - Horde - Alchemy 3
    [1413] = { exp = 5 }, -- Garrison - Horde - Blacksmith 2
    [1414] = { exp = 5 }, -- Garrison - Horde - Blacksmith 3
    [1415] = { exp = 5 }, -- Garrison - Horde - Enchanting 2
    [1416] = { exp = 5 }, -- Garrison - Horde - Enchanting 3
    [1417] = { exp = 5 }, -- Garrison - Horde - Inscription 2
    [1418] = { exp = 5 }, -- Garrison - Horde - Inscription 3
    [1419] = { exp = 5 }, -- Garrison - Horde - Leatherworking 2
    [1420] = { exp = 5 }, -- Garrison - Horde - Leatherworking 3
    [1421] = { exp = 5 }, -- Garrison - Horde - Jewelcrafting 2
    [1422] = { exp = 5 }, -- Garrison - Horde - Jewelcrafting 3
    [1423] = { exp = 5 }, -- Garrison - Horde - Tailoring 2
    [1424] = { exp = 5 }, -- Garrison - Horde - Tailoring 3
    [1425] = { exp = 5 }, -- Garrison - Horde - Salvage Yard 2
    [1426] = { exp = 5 }, -- Garrison - Horde - Salvage Yard 3
    [1427] = { exp = 5 }, -- PattyMack Test Garrison Bld Map2
    [1429] = { exp = 5 }, -- Garrison - Horde - Engineering 2
    [1430] = { exp = 5 }, -- Garrison - Horde - Engineering 3
    [1431] = { ls = 1035009, exp = 5 }, -- The Coliseum
    [1432] = { exp = 5 }, -- Garrison - Horde - Fishing 2
    [1433] = { exp = 5 }, -- Garrison - Horde - Fishing 3
    [1434] = { exp = 5 }, -- Garrison - Alliance - Fishing 2
    [1435] = { exp = 5 }, -- Garrison - Alliance - Fishing 3
    [1437] = { exp = 5 }, -- Garrison - Alliance - Pet Stable 1
    [1438] = { exp = 5 }, -- Garrison - Alliance - Pet Stable 2
    [1439] = { exp = 5 }, -- Garrison - Alliance - Pet Stable 3
    [1440] = { exp = 0 }, -- Garrison - Alliance - Infirmary 1
    [1441] = { exp = 0 }, -- Garrison - Alliance - Infirmary 2
    [1442] = { exp = 0 }, -- Garrison - Alliance - Infirmary 3
    [1446] = { exp = 5 }, -- Outdoor Garrison - Construction Plot, La
    [1447] = { exp = 5 }, -- Outdoor Garrison - Construction Plot, La
    [1448] = { ls = 1132136, exp = 5 }, -- Hellfire Citadel
    [1451] = { exp = 5 }, -- Tanaan Legion Test
    [1454] = { ls = 320915, exp = 6 }, -- The Broken Shore (old - delete)
    [1455] = { ls = 1033059, exp = 5 }, -- Edge of Reality
    [1456] = { ls = 1467575, exp = 6 }, -- Eye of Azshara
    [1458] = { ls = 1445178, exp = 6 }, -- Neltharion's Lair
    [1459] = { exp = 5 }, -- Transport: The Iron Mountain
    [1460] = { ls = 1446595, exp = 5 }, -- Broken Shore Scenario
    [1461] = { ls = 1446595, exp = 6 }, -- Azsuna Scenario
    [1462] = { exp = 6 }, -- Illidans Rock
    [1463] = { ls = 1446595, exp = 6 }, -- Helhiem Exterior Area
    [1464] = { ls = 1035009, exp = 5 }, -- Tanaan Jungle
    [1465] = { ls = 1035009, exp = 5 }, -- Tanaan Jungle - No Hubs Phase
    [1466] = { ls = 1389212, exp = 6 }, -- Darkheart Thicket
    [1468] = { ls = 1389449, exp = 5 }, -- Warden Prison DH Quests
    [1469] = { ls = 1405662, exp = 3 }, -- The Heart of Azeroth
    [1471] = { exp = 0 }, -- Dungeon Test Map 1466
    [1473] = { ls = 1035009, exp = 5 }, -- Garrison - Alliance - Shipyard
    [1474] = { ls = 1035009, exp = 5 }, -- Garrison - Horde - Shipyard
    [1475] = { exp = 6 }, -- The Maw of Nashal
    [1476] = { exp = 6 }, -- Transport: The Maw of Nashal
    [1477] = { ls = 1454826, exp = 6 }, -- Halls of Valor
    [1478] = { ls = 131843, exp = 6 }, -- The Temple of Elune
    [1479] = { ls = 1454826, exp = 6 }, -- Skyhold
    [1480] = { ls = 318964, exp = 6 }, -- Icecrown Citadel
    [1481] = { ls = 1303234, exp = 5 }, -- Mardum
    [1482] = { exp = 5 }, -- Garrison Shipyard - Submarine - Alliance
    [1483] = { exp = 5 }, -- Garrison Shipyard - Destroyer - Alliance
    [1484] = { exp = 5 }, -- Garrison Shipyard - Transport
    [1485] = { exp = 5 }, -- Garrison Shipyard - Battleship - Allianc
    [1486] = { exp = 5 }, -- Garrison Shipyard - Carrier - Horde
    [1487] = { exp = 5 }, -- Garrison Shipyard - Submarine - Horde
    [1488] = { exp = 5 }, -- Garrison Shipyard - Destroyer - Horde
    [1489] = { ls = 1395043, exp = 6 }, -- Niskara
    [1492] = { ls = 1391080, exp = 6 }, -- Maw of Souls
    [1493] = { ls = 1389449, exp = 6 }, -- Vault of the Wardens
    [1494] = { ls = 1496467, exp = 6 }, -- The Violet Hold
    [1495] = { ls = 1446595, exp = 6 }, -- Shield's Rest
    [1496] = { exp = 5 }, -- Garrison Shipyard - Carrier - Alliance
    [1497] = { exp = 5 }, -- Garrison Shipyard - Battleship - Horde
    [1498] = { ls = 1446595, exp = 6 }, -- Felsoul Hold
    [1500] = { ls = 1446595, exp = 6 }, -- Broken Shore
    [1501] = { ls = 1399464, exp = 6 }, -- Black Rook Hold
    [1502] = { ls = 1446595, exp = 6 }, -- Dalaran Underbelly
    [1503] = { ls = 424078, exp = 6 }, -- Deepholm
    [1504] = { ls = 1451468, exp = 6 }, -- Black Rook Hold Arena
    [1505] = { ls = 1536931, exp = 6 }, -- Nagrand Arena
    [1509] = { exp = 6 }, -- Bloodtotem Cavern - Fel Phase
    [1510] = { exp = 6 }, -- Bloodtotem Cavern - Tauren Phase
    [1511] = { ls = 1446595, exp = 6 }, -- Tideskorn Harbor
    [1512] = { ls = 1412500, exp = 6 }, -- Netherlight Temple
    [1513] = { ls = 1445353, exp = 6 }, -- Hall of the Guardian
    [1514] = { ls = 1375895, exp = 6 }, -- The Wandering Isle
    [1515] = { ls = 1498775, exp = 6 }, -- Huln's War
    [1516] = { ls = 1395129, exp = 6 }, -- The Arcway
    [1517] = { exp = 6 }, -- Stormheim Prescenario Windrunner
    [1518] = { exp = 6 }, -- Stormheim Prescenario Skyfire
    [1519] = { ls = 1389211, exp = 6 }, -- The Fel Hammer
    [1520] = { ls = 1394867, exp = 6 }, -- The Emerald Nightmare
    [1522] = { ls = 1394926, exp = 6 }, -- Dreadscar Rift
    [1523] = { ls = 1389211, exp = 6 }, -- Defense of the Fel Hammer Scenario
    [1526] = { ls = 795305, exp = 6 }, -- Temple of the White Tiger
    [1527] = { ls = 1446595, exp = 6 }, -- High Mountain Scenario
    [1528] = { ls = 402550, exp = 6 }, -- Skywall
    [1529] = { ls = 131849, exp = 5 }, -- Karazhan
    [1530] = { ls = 1448532, exp = 6 }, -- The Nighthold
    [1532] = { ls = 1446595, exp = 6 }, -- High Mountain Mesa Scenario
    [1533] = { ls = 131849, exp = 6 }, -- Karazhan Catacombs
    [1534] = { ls = 1498775, exp = 6 }, -- Moonglade
    [1535] = { exp = 6 }, -- Moonglade
    [1536] = { ls = 1389212, exp = 6 }, -- Ursocs Lair
    [1538] = { ls = 131849, exp = 0 }, -- test
    [1539] = { ls = 1498773, exp = 6 }, -- Tirisfal Glades
    [1540] = { ls = 1476725, exp = 6 }, -- Emerald Dreamway
    [1541] = { ls = 643909, exp = 6 }, -- Terrace of Endless Spring
    [1544] = { ls = 1496467, exp = 6 }, -- Assault on Violet Hold
    [1545] = { ls = 1446595, exp = 6 }, -- Azsuna
    [1547] = { ls = 1446595, exp = 6 }, -- Artifact - Combat - Acquisition Ship
    [1552] = { ls = 1472862, exp = 6 }, -- Ashamane's Fall
    [1553] = { ls = 1446595, exp = 6 }, -- Gloaming Reef
    [1554] = { ls = 1446595, exp = 5 }, -- 7.0 Boost Experience - Alliance
    [1555] = { exp = 6 }, -- zzOLD - Transport: Boost Experience - Al
    [1556] = { exp = 6 }, -- zzOLD - Transport: Boost Experience - Ho
    [1557] = { ls = 1446595, exp = 5 }, -- 7.0 Boost Experience - Horde
    [1559] = { exp = 5 }, -- 7.0 Transport: Boost Experience - Horde 
    [1560] = { exp = 5 }, -- 7.0 Transport: Boost Experience - Allian
    [1571] = { ls = 1477131, exp = 6 }, -- Court of Stars
    [1572] = { ls = 512032, exp = 3 }, -- The Maelstrom
    [1579] = { ls = 131879, exp = 5 }, -- Ulduar
    [1580] = { ls = 512032, exp = 6 }, -- The Maelstrom
    [1582] = { exp = 6 }, -- Delete
    [1583] = { ls = 131857, exp = 6 }, -- Nexus Vault
    [1586] = { ls = 1498773, exp = 6 }, -- Assault on Stormwind
    [1592] = { ls = 7864815, exp = 11 }, -- Sporefall
    [1594] = { ls = 2016712, exp = 7 }, -- The MOTHERLODE!!
    [1599] = { ls = 1498775, exp = 6 }, -- Nordrassil
    [1600] = { ls = 397151, exp = 6 }, -- Throne of the Tides (Artifact Scenario)
    [1602] = { ls = 402550, exp = 6 }, -- Artifact - The Vortex Pinnacle - Shaman 
    [1603] = { ls = 397151, exp = 3 }, -- Throne of the Tides Scenario(DELETE)
    [1604] = { ls = 1395043, exp = 6 }, -- Artifact - Order Campaign - Portal World
    [1605] = { ls = 514085, exp = 6 }, -- Firelands_Artifact
    [1607] = { ls = 1303234, exp = 6 }, -- Artifact - Acquisition - Subtlety
    [1608] = { ls = 1498775, exp = 6 }, -- Hyjal War of the Ancients Quest
    [1609] = { ls = 447134, exp = 6 }, -- Temple of Storms
    [1610] = { ls = 651994, exp = 6 }, -- Artifact - Serenity Legion Scenario
    [1611] = { ls = 1498773, exp = 6 }, -- Death Knight Campaign - Light's Hope Cha
    [1612] = { ls = 1472862, exp = 6 }, -- The Ruins of Falanaar
    [1616] = { ls = 1446595, exp = 6 }, -- Faronaar
    [1617] = { ls = 1272474, exp = 6 }, -- Death Knight Campaign - Undercity
    [1618] = { exp = 6 }, -- Death Knight Campaign - Scarlet Monaster
    [1620] = { ls = 1498773, exp = 6 }, -- Artifact - Stormwind
    [1621] = { ls = 131826, exp = 6 }, -- Black Temple - Legion
    [1622] = { ls = 1446595, exp = 6 }, -- Telogrus Rift Scenario
    [1623] = { ls = 131857, exp = 6 }, -- Mage Campaign - The Oculus
    [1624] = { ls = 1498775, exp = 6 }, -- Battle of Exodar
    [1625] = { ls = 633149, exp = 6 }, -- Trial of the Serpent
    [1626] = { ls = 1446595, exp = 6 }, -- The Collapse - Suramar Scenario
    [1627] = { exp = 6 }, -- Fel Hammer DH Scenario
    [1628] = { exp = 6 }, -- Transport: Alliance Battleship
    [1629] = { ls = 1412500, exp = 6 }, -- Netherlight Temple
    [1630] = { ls = 411683, exp = 6 }, -- Tol Barad
    [1632] = { ls = 1395129, exp = 6 }, -- The Arcway - Suramar Scenario
    [1637] = { exp = 6 }, -- Transport: Alliance Ship PhaseableMO
    [1638] = { exp = 6 }, -- Transport: Horde Ship PhaseableMO
    [1639] = { exp = 6 }, -- Transport: Kvaldir Ship PhaseableMO
    [1642] = { ls = 2143606, exp = 7 }, -- Zandalar
    [1643] = { ls = 2143605, exp = 7 }, -- Kul Tiras
    [1644] = { exp = 6 }, -- Plunder Isle
    [1646] = { ls = 1399464, exp = 6 }, -- Black Rook Hold [Scenario]
    [1647] = { exp = 6 }, -- Vol'jin's Funeral Pyre
    [1648] = { ls = 1537273, exp = 6 }, -- Trial of Valor
    [1649] = { exp = 6 }, -- Transport: Horde Battleship
    [1650] = { exp = 6 }, -- Legion Command Ship Transport
    [1651] = { ls = 1537272, exp = 6 }, -- Return to Karazhan
    [1653] = { ls = 1446595, exp = 6 }, -- Great Dark Beyond
    [1657] = { ls = 131828, exp = 6 }, -- zzOldBlade's Edge Arena
    [1662] = { exp = 6 }, -- Suramar
    [1666] = { ls = 1446595, exp = 6 }, -- The Assault on Broken Shore
    [1667] = { ls = 1446595, exp = 6 }, -- Legion Ship - Vertical
    [1668] = { ls = 1446595, exp = 6 }, -- Legion Ship - Horizontal
    [1669] = { ls = 1719332, exp = 6 }, -- Argus
    [1670] = { ls = 1446595, exp = 6 }, -- Broken Shore (Delete)
    [1671] = { ls = 1446595, exp = 6 }, -- Broken Shore - Prepatch 7.2 (Backup)
    [1672] = { ls = 1568178, exp = 6 }, -- Blade's Edge Arena
    [1673] = { ls = 236062, exp = 6 }, -- The Eye of Eternity - Scenario
    [1675] = { ls = 1446595, exp = 6 }, -- Winter AB_old
    [1676] = { ls = 1615560, exp = 6 }, -- Tomb of Sargeras
    [1677] = { ls = 1616802, exp = 6 }, -- Cathedral of Eternal Night
    [1678] = { ls = 1446595, exp = 6 }, -- AB Phase 1
    [1679] = { ls = 1446595, exp = 6 }, -- AB Phase 2
    [1680] = { ls = 1446595, exp = 6 }, -- AB Phase 3
    [1681] = { ls = 1608214, exp = 6 }, -- Arathi Basin Winter
    [1682] = { ls = 1389211, exp = 6 }, -- The Fel Hammer Terrain Phase
    [1683] = { ls = 131841, exp = 6 }, -- Artifact - Gnomeregan
    [1684] = { ls = 1394926, exp = 6 }, -- Dread Scar Rift - Warlock Scenario Platf
    [1687] = { ls = 131882, exp = 0 }, -- Wailing Caverns
    [1688] = { ls = 131833, exp = 0 }, -- Deadmines
    [1689] = { ls = 236062, exp = 6 }, -- The Eye of Eternity - Mage Class Mount
    [1691] = { ls = 875627, exp = 7 }, -- Cooking: Impossible
    [1692] = { ls = 335909, exp = 6 }, -- Pit of Saron - Death Knight Campaign
    [1693] = { ls = 633156, exp = 6 }, -- Stormstout Brewery - Monk Scenario
    [1694] = { ls = 131841, exp = 0 }, -- Gnomeregan
    [1695] = { ls = 1446595, exp = 6 }, -- Battleship: Ruin
    [1696] = { exp = 6 }, -- Legion - Command Center
    [1697] = { exp = 6 }, -- Legion - Legion Spider Cave
    [1698] = { ls = 1446595, exp = 6 }, -- Artifact - Acquisition - Tank
    [1699] = { exp = 6 }, -- Legion - Legion Fel Cave
    [1700] = { exp = 6 }, -- Legion - Legion Fel Firenova Area
    [1701] = { exp = 6 }, -- Legion - Legion Barracks
    [1702] = { ls = 1445178, exp = 6 }, -- Artifact - Highmountain - Dual Boss
    [1703] = { ls = 1454826, exp = 6 }, -- Halls of Valor - Scenario
    [1704] = { ls = 1446595, exp = 6 }, -- Legion Ship - Horizontal - Valsharah
    [1705] = { ls = 1446595, exp = 6 }, -- Legion Ship - Horizontal - Azsuna
    [1706] = { ls = 1446595, exp = 6 }, -- Legion Ship - Vertical - HighMountain
    [1707] = { ls = 1446595, exp = 6 }, -- Legion Ship - Vertical - Stormheim
    [1708] = { ls = 131871, exp = 6 }, -- Stratholme - Paladin Class Mount
    [1710] = { ls = 1399464, exp = 6 }, -- Black Rook Hold - Artifact Challenge
    [1711] = { exp = 0 }, -- Alliance Submarine (7.1.5 Boat Holiday)
    [1712] = { ls = 1717773, exp = 6 }, -- Antorus, the Burning Throne
    [1714] = { ls = 1454826, exp = 6 }, -- Halls Of Valor - Warrior Class Mount
    [1716] = { exp = 6 }, -- Broken Shore Mage Tower
    [1718] = { ls = 3008537, exp = 7 }, -- Nazjatar
    [1719] = { ls = 1394926, exp = 6 }, -- Dread Scar Rift - Warlock Mount Scenario
    [1723] = { ls = 1498773, exp = 6 }, -- Coldridge Valley
    [1728] = { ls = 1454826, exp = 6 }, -- Halls of Valor
    [1729] = { ls = 236062, exp = 6 }, -- The Eye of Eternity - Mage Class Mount (
    [1730] = { ls = 1498775, exp = 6 }, -- Shrine of Aviana Defense - Scenario
    [1731] = { ls = 1446595, exp = 6 }, -- Druid Mount Finale - Scenario
    [1732] = { ls = 1389211, exp = 6 }, -- Felwing Ledge - Demon Hunter Class Mount
    [1733] = { ls = 1498773, exp = 6 }, -- Azeroth's Warning Scenario
    [1734] = { ls = 450109, exp = 6 }, -- Throne of the Four Winds - Shaman Class 
    [1735] = { ls = 447134, exp = 6 }, -- Frozen Wastes
    [1736] = { ls = 365622, exp = 6 }, -- The Ruby Sanctum
    [1737] = { ls = 1446595, exp = 6 }, -- Pocket Dimension Akazamzaraks Hat Scenar
    [1738] = { ls = 447134, exp = 6 }, -- The Lost Glacier
    [1741] = { exp = 6 }, -- The Vindicaar
    [1744] = { ls = 131874, exp = 6 }, -- Trial of Style
    [1746] = { ls = 131875, exp = 6 }, -- Tempest Keep: The Arcatraz
    [1750] = { ls = 447135, exp = 6 }, -- Azuremyst Isle
    [1751] = { exp = 6 }, -- Alliance Battleship (7.3 Intro)
    [1752] = { exp = 6 }, -- Sunstrider Battleship (7.3 Intro)
    [1753] = { ls = 1717768, exp = 6 }, -- Seat of the Triumvirate
    [1754] = { ls = 2125650, exp = 7 }, -- Freehold
    [1756] = { ls = 1672553, exp = 6 }, -- The Deaths of Chromie
    [1760] = { ls = 1498773, exp = 6 }, -- Lordaeron
    [1762] = { ls = 2000399, exp = 7 }, -- Kings' Rest
    [1763] = { ls = 1968998, exp = 7 }, -- Atal'Dazar
    [1764] = { ls = 652548, exp = 6 }, -- Endless Halls
    [1771] = { ls = 1969119, exp = 7 }, -- Tol Dagor
    [1773] = { ls = 1498773, exp = 0 }, -- Shadow of Azeroth
    [1774] = { ls = 1446595, exp = 0 }, -- Forge of Aeons
    [1775] = { exp = 6 }, -- Maw of N'Zoth
    [1776] = { exp = 7 }, -- Horde Battleship - The Banshee's Wail
    [1779] = { exp = 6 }, -- Invasion Points
    [1785] = { exp = 7 }, -- 8.0 Islands - Ship - Pirateship
    [1786] = { exp = 7 }, -- 8.0 Islands - Zeppelin - Goblin
    [1787] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [1795] = { ls = 651994, exp = 7 }, -- Vale of Eternal Blossoms
    [1803] = { ls = 1864572, exp = 6 }, -- Seething Shore
    [1806] = { exp = 7 }, -- Alliance Battleship -  Wind's Redemption
    [1812] = { exp = 6 }, -- Suramar
    [1813] = { ls = 2139069, exp = 7 }, -- Un'gol Ruins (Islands 1)
    [1814] = { ls = 2139069, exp = 7 }, -- Havenswood (Islands 2)
    [1815] = { ls = 1498775, exp = 6 }, -- Silithus Phase
    [1817] = { ls = 1498775, exp = 0 }, -- Silithus: The Wound
    [1818] = { exp = 0 }, -- Silvermoon City
    [1822] = { ls = 2068775, exp = 7 }, -- Siege of Boralus
    [1825] = { ls = 2033044, exp = 7 }, -- Hook Point
    [1839] = { ls = 131849, exp = 7 }, -- Karazan Chess
    [1840] = { ls = 1446595, exp = 6 }, -- The Sunwell
    [1841] = { ls = 2175832, exp = 7 }, -- The Underrot
    [1844] = { exp = 7 }, -- 8.0 Islands - Event
    [1845] = { exp = 7 }, -- 8.0 Islands - Event
    [1846] = { exp = 7 }, -- 8.0 Islands - Ship - 6HU Cargoship
    [1850] = { exp = 7 }, -- 8.2.5 - MSEM - 1850
    [1851] = { exp = 7 }, -- 8.0 Islands - Ship - 7FK Buccaneer
    [1855] = { ls = 1446595, exp = 6 }, -- The Vindicaar
    [1856] = { exp = 6 }, -- Transport: Azerite BG - Alliance Airship
    [1857] = { exp = 6 }, -- Transport: Azerite BG - Horde Gunship
    [1860] = { ls = 1446595, exp = 6 }, -- The Vindicaar
    [1861] = { ls = 2126830, exp = 7 }, -- Uldir
    [1862] = { ls = 1984118, exp = 7 }, -- Waycrest Manor
    [1864] = { ls = 2103733, exp = 7 }, -- Shrine of the Storm
    [1865] = { ls = 1446595, exp = 6 }, -- Telogrus Rift
    [1876] = { ls = 2103696, exp = 7 }, -- Warfronts Arathi - Horde
    [1877] = { ls = 2061464, exp = 7 }, -- Temple of Sethraliss
    [1879] = { ls = 2139069, exp = 7 }, -- Jorundall (Islands 7)
    [1882] = { ls = 2139069, exp = 7 }, -- Verdant Wilds (Islands 8)
    [1883] = { ls = 2139069, exp = 7 }, -- Whispering Reef (Islands 10)
    [1884] = { ls = 903869, exp = 7 }, -- Siege of Orgrimmar - Mag'har Orc Unlock 
    [1892] = { ls = 2139069, exp = 7 }, -- The Rotting Mire (Islands 9)
    [1893] = { ls = 2139069, exp = 7 }, -- The Dread Chain (Islands 4)
    [1897] = { ls = 2139069, exp = 7 }, -- Molten Cay (Islands 6)
    [1898] = { ls = 2139069, exp = 7 }, -- Skittering Hollow (Islands 5)
    [1902] = { exp = 6 }, -- Silithus Alliance Gunship
    [1903] = { exp = 6 }, -- Silithus Horde Gunship
    [1904] = { ls = 1498773, exp = 7 }, -- Stormwind Escape from Stockades
    [1906] = { ls = 1780110, exp = 7 }, -- Zandalar Continent Finale
    [1907] = { ls = 2139069, exp = 7 }, -- Snowblossom Village (Islands 3)
    [1909] = { exp = 7 }, -- [UNUSED] Transport: Kul Tiras - Bridgepo
    [1910] = { exp = 7 }, -- Transport: Kul Tiras - Bridgeport - The 
    [1911] = { ls = 2103695, exp = 7 }, -- Mugambala
    [1913] = { exp = 7 }, -- PhaseableMO: Nazmir - Triangulation Plat
    [1916] = { exp = 7 }, -- PhaseableMO: Nazmir - Ship World Quest
    [1917] = { ls = 1035009, exp = 7 }, -- Gorgrond - Mag'har Scenario
    [1918] = { ls = 1498775, exp = 7 }, -- Kalimdor Darkshore Phase
    [1919] = { exp = 7 }, -- 8.0 Islands - Platform - KL Skywall Entr
    [1920] = { exp = 7 }, -- 8.0 Islands - Platform - MD Flamegate E
    [1921] = { exp = 7 }, -- 8.0 Islands - Ship - Player Alliance - K
    [1922] = { exp = 7 }, -- 8.0 Islands - Ship - Player Horde - Zand
    [1923] = { exp = 7 }, -- 8.0 Islands - Platform - Deepholm Mercur
    [1924] = { exp = 7 }, -- 8.0 Islands - Platform - 7AZ Vashjir Sma
    [1926] = { exp = 7 }, -- 8.1.5 Allies - Kul Tiran Flagship (JAK)
    [1927] = { exp = 7 }, -- Zandalari Flagship
    [1929] = { ls = 1780110, exp = 7 }, -- Chamber of Heart
    [1930] = { ls = 1780110, exp = 7 }, -- Zandalar Alliance Intro Scenario
    [1931] = { ls = 1498773, exp = 6 }, -- Lordaeron Blight
    [1932] = { ls = 131824, exp = 7 }, -- Blackrock Depths - Dark Iron Scenario
    [1935] = { exp = 7 }, -- 8.0 Islands - Cave - 8KUL_CaveMicro01
    [1936] = { exp = 7 }, -- 8.0 Islands - Cave - 8KUL_CaveMicro02
    [1937] = { exp = 7 }, -- 8.0 Islands - Cave - 8KUL_CaveMicro03
    [1938] = { exp = 7 }, -- 8.0 Islands - Cave - 8RIV_CaveMicro_01
    [1939] = { exp = 7 }, -- 8.0 Islands - Cave - 8RIV_CaveMicro_02
    [1940] = { exp = 7 }, -- Alliance Battleship -  Wind's Redemption
    [1941] = { ls = 1780110, exp = 7 }, -- Transport: Nazmir Raid Elevator
    [1942] = { ls = 131851, exp = 7 }, -- Molten Core
    [1943] = { ls = 2103696, exp = 7 }, -- Warfronts Arathi - Alliance
    [1944] = { ls = 1780110, exp = 7 }, -- Thros, The Blighted Lands
    [1945] = { ls = 1780110, exp = 7 }, -- Arathi Highlands 2
    [1949] = { ls = 3807424, exp = 7 }, -- 8.0 Boost Experience - Alliance
    [1950] = { ls = 3807424, exp = 7 }, -- 8.0 Boost Experience - Horde
    [1951] = { exp = 7 }, -- 8.0 Transport: Boost Experience - Allian
    [1952] = { exp = 5 }, -- 8.0 Transport: Boost Experience - Horde 
    [1953] = { exp = 7 }, -- 8.0 Islands - Platform - demigod dome li
    [1954] = { exp = 7 }, -- The Great Sea Alliance
    [1955] = { ls = 2139069, exp = 6 }, -- Uncharted Island
    [1956] = { exp = 7 }, -- 8.0 Islands - Platform - Hot Old God 03
    [1957] = { exp = 7 }, -- 8.0 Islands - Platform - Old God
    [1958] = { exp = 7 }, -- The Golden Skipper - Zandalari Transport
    [1959] = { exp = 7 }, -- Zandalari Transport Ship Large
    [1962] = { exp = 7 }, -- Goblin Ship Final
    [1964] = { exp = 7 }, -- PhaseableMO: War Campaign - Horde - Chap
    [1965] = { exp = 7 }, -- PhaseableMO: War Campaign - Horde - Chap
    [2066] = { exp = 7 }, -- The Great Sea Horde
    [2067] = { exp = 7 }, -- Zandalari Battleship - Gral's Call
    [2069] = { exp = 7 }, -- Zuldazar Alliance Bombing Run
    [2070] = { ls = 2530069, exp = 7 }, -- Battle of Dazar'alor
    [2074] = { exp = 7 }, -- 8.0 Transport: Boralus to Stormwind
    [2075] = { exp = 7 }, -- 8.0 Islands - Event
    [2076] = { ls = 514085, exp = 7 }, -- Firelands - Dark Iron Dwarf
    [2077] = { exp = 7 }, -- 8.0 Islands - Event
    [2078] = { exp = 7 }, -- 8.0 Islands - Event
    [2081] = { ls = 131824, exp = 7 }, -- Blackrock Depths - Dark Iron Dwarf Hub
    [2082] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [2083] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [2084] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [2085] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [2086] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [2087] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [2088] = { exp = 7 }, -- 8.0 Islands - Micro - Mogu Crypt
    [2094] = { exp = 7 }, -- 8.0 Transport: Boralus Canals
    [2095] = { exp = 7 }, -- 8.0 Transport: Boralus Sound
    [2096] = { ls = 2494959, exp = 7 }, -- Crucible of Storms
    [2097] = { ls = 2991615, exp = 7 }, -- Operation: Mechagon
    [2101] = { exp = 7 }, -- 8.0 Transport: Boralus Barge
    [2102] = { exp = 7 }, -- 8.0 Transport: Boralus Ship Small
    [2103] = { exp = 7 }, -- Darkshore Prepatch Darnassian Ship
    [2105] = { ls = 2529512, exp = 7 }, -- Warfronts Darkshore - Alliance
    [2106] = { ls = 2827086, exp = 0 }, -- Warsong Gulch
    [2161] = { exp = 0 }, -- Maw Prototype - Torment Chambers
    [2162] = { ls = 3760516, exp = 8 }, -- Torghast, Tower of the Damned
    [2107] = { ls = 2820825, exp = 0 }, -- Arathi Basin
    [2109] = { exp = 7 }, -- 8.1.0 Incursion Airship Horde
    [2110] = { exp = 7 }, -- 8.1.0 Incursion Airship Alliance
    [2111] = { ls = 2529512, exp = 7 }, -- Warfronts Darkshore - Horde
    [2114] = { ls = 1498775, exp = 7 }, -- Maw Prototype
    [2115] = { ls = 1780110, exp = 7 }, -- 8.1 Darkshore Scenario
    [2118] = { ls = 236065, exp = 2 }, -- Battle for Wintergrasp
    [2119] = { exp = 7 }, -- Transport: Cooking: Impossible - Hot Air
    [2120] = { exp = 7 }, -- Transport: Cooking: Impossible - Hot Air
    [2123] = { ls = 2494959, exp = 7 }, -- Shrine of the Storm Quests
    [2124] = { ls = 2139069, exp = 7 }, -- Crestfall (Islands 11)
    [2125] = { ls = 2143606, exp = 7 }, -- Zandalari Treasury
    [2127] = { ls = 6225617, exp = 10 }, -- Siren Isle
    [2128] = { ls = 1780110, exp = 7 }, -- Dagger Realm
    [2129] = { ls = 1780110, exp = 7 }, -- 8.1 Darkshore Horde Quests
    [2131] = { ls = 1780110, exp = 7 }, -- 8.1 Darkshore Outdoor Final Phase
    [2134] = { ls = 1969119, exp = 7 }, -- Tol Dagor Scenario
    [2136] = { exp = 0 }, -- Transport: Zuldazar Raid Ship
    [2145] = { exp = 7 }, -- Transport: Night Elf Warship
    [2146] = { exp = 7 }, -- Transport: Forsaken Warship
    [2147] = { ls = 318964, exp = 7 }, -- Icecrown Citadel (8.1)
    [2155] = { exp = 7 }, -- Halls of Stone Scenario
    [2160] = { exp = 0 }, -- Maw Prototype - Dragonblight
    [2163] = { exp = 7 }, -- Gnomeregan Scenario
    [2164] = { ls = 3006757, exp = 7 }, -- The Eternal Palace
    [2165] = { exp = 7 }, -- SpawnedMO: Night Elf Warship
    [2166] = { exp = 0 }, -- Transport: Zuldazar Raid Boralus Ship
    [2167] = { ls = 2999376, exp = 7 }, -- The Robodrome
    [2169] = { ls = 2126830, exp = 7 }, -- Uldir Scenario
    [2170] = { exp = 7 }, -- Tauren Heritage Scenario
    [2174] = { ls = 643908, exp = 7 }, -- Scarlet Halls, Dark Ranger
    [2175] = { ls = 3683676, exp = 7 }, -- 9.0 NPE (New Player Experience) - Exile'
    [2176] = { exp = 7 }, -- SpawnedMO: Forsaken Ship Large
    [2177] = { ls = 2820825, exp = 7 }, -- Arathi Basin Comp Stomp
    [2178] = { ls = 1780110, exp = 7 }, -- The Prison of Ink
    [2179] = { ls = 131871, exp = 7 }, -- Stratholme Pet Dungeon
    [2180] = { ls = 1446595, exp = 6 }, -- The Dreamgrove (Hearthstone Tavern)
    [2186] = { ls = 236057, exp = 7 }, -- The Obsidian Sanctum - 8.2 Magni - Heart
    [2187] = { ls = 400719, exp = 7 }, -- Halls of Origination
    [2193] = { ls = 447134, exp = 7 }, -- Galakrond's Fall
    [2194] = { exp = 7 }, -- Hearthstone Tavern
    [2195] = { ls = 7266212, exp = 11 }, -- Arcantina
    [2197] = { ls = 131861, exp = 0 }, -- Korrak's Revenge
    [2205] = { exp = 7 }, -- 9.0 Transport: Zone Transition Test
    [2207] = { ls = 1445178, exp = 7 }, -- Neltharion's Lair - HoA Scenario
    [2208] = { ls = 1498775, exp = 7 }, -- Eastern Kingdoms - Vermillion Redoubt - 
    [2209] = { ls = 1476725, exp = 7 }, -- Emerald Dream - HoA Scenario
    [2210] = { ls = 1013075, exp = 7 }, -- Siege of Orgrimmar - Coup Scenario
    [2211] = { exp = 7 }, -- Gilneas - Worgen Heritage Scenario
    [2212] = { ls = 3195545, exp = 7 }, -- Horrific Vision of Orgrimmar
    [2213] = { ls = 3195545, exp = 7 }, -- Horrific Vision of Stormwind
    [2214] = { ls = 512032, exp = 7 }, -- The Maelstrom - Heart of Azeroth
    [2215] = { ls = 1780110, exp = 7 }, -- Chamber of Heart - Repaired
    [2217] = { ls = 3170732, exp = 7 }, -- Ny'alotha, the Waking City
    [2222] = { ls = 3807424, exp = 8 }, -- The Shadowlands
    [2223] = { ls = 236062, exp = 7 }, -- The Eye of Eternity - HoA Scenario
    [2232] = { ls = 131849, exp = 7 }, -- Karazhan Catacombs - HoA Scenario
    [2233] = { ls = 633149, exp = 7 }, -- Temple of the Jade Serpent - HoA Scenari
    [2235] = { ls = 131830, exp = 7 }, -- Caverns of Time - Anniversary
    [2236] = { ls = 3635651, exp = 7 }, -- Darkmaul Citadel
    [2237] = { exp = 7 }, -- 8.2.5 Orgrimmar
    [2241] = { ls = 1498775, exp = 7 }, -- Uldum
    [2245] = { ls = 875627, exp = 4 }, -- Deepwind Gorge
    [2246] = { exp = 7 }, -- Solesa Naksu [DNT]
    [2247] = { ls = 633150, exp = 7 }, -- Mogu'shan Scenario
    [2257] = { ls = 1780110, exp = 7 }, -- Chamber of Heart - Scenario
    [2258] = { ls = 2016712, exp = 7 }, -- Crapopolis - Scenario
    [2261] = { exp = 7 }, -- 9.0 Transport - NPE - Alliance Battleshi
    [2263] = { ls = 2016712, exp = 7 }, -- Crapopolis
    [2264] = { exp = 7 }, -- Visions of N'Zoth - Orgrimmar - Engineer
    [2266] = { ls = 404445, exp = 7 }, -- Blackwing Descent Scenario
    [2267] = { ls = 2991615, exp = 7 }, -- city
    [2268] = { ls = 2991615, exp = 7 }, -- Mechagon City
    [2274] = { ls = 3195545, exp = 7 }, -- Vision of the Twisting Sands
    [2275] = { ls = 3195545, exp = 7 }, -- Vale of Eternal Twilight
    [2276] = { ls = 3807424, exp = 8 }, -- 9.0 Transport - Maldraxxus Necropolis [T
    [2277] = { ls = 3807424, exp = 8 }, -- 9.0 SpawnedMO - Maldraxxus Necropolis [W
    [2278] = { ls = 3582016, exp = 8 }, -- Revendreth Scenario
    [2282] = { ls = 131824, exp = 0 }, -- Blackrock Depths - Pet Dungeon
    [2284] = { ls = 3565435, exp = 8 }, -- Sanguine Depths
    [2285] = { ls = 3621966, exp = 8 }, -- Spires of Ascension
    [2286] = { ls = 3615757, exp = 8 }, -- The Necrotic Wake
    [2287] = { ls = 3721473, exp = 8 }, -- Halls of Atonement
    [2289] = { ls = 3602023, exp = 8 }, -- Plaguefall
    [2290] = { ls = 3642564, exp = 8 }, -- Mists of Tirna Scithe
    [2291] = { ls = 3638598, exp = 8 }, -- De Other Side
    [2293] = { ls = 3685314, exp = 8 }, -- Theater of Pain
    [2294] = { ls = 131830, exp = 8 }, -- [NOT USED] Realm
    [2296] = { ls = 3582016, exp = 8 }, -- Castle Nathria
    [2297] = { ls = 318964, exp = 7 }, -- Icecrown Citadel (8.3)
    [2299] = { exp = 8 }, -- Vision of Ysera Scenario
    [2300] = { ls = 1498773, exp = 8 }, -- Redridge - 9xp Bastion
    [2303] = { ls = 3807424, exp = 8 }, -- Ardenweald Zone Scenario
    [2304] = { ls = 3807424, exp = 8 }, -- Ardenweald Tyrande Finale Scenario
    [2305] = { ls = 3807424, exp = 8 }, -- Bastion Scenario
    [2308] = { ls = 3807424, exp = 0 }, -- Bastion Night Warrior Finale - Ardenweal
    [2309] = { exp = 8 }, -- Transport: Torghast Bridge Platform01 El
    [2354] = { ls = 3807424, exp = 8 }, -- Ardenweald Covenant Chapter 2 Scenario
    [2355] = { ls = 3615757, exp = 8 }, -- The Necrotic Wake (Transport)
    [2356] = { ls = 3582016, exp = 8 }, -- Castle Nathria Scenario
    [2360] = { ls = 3582016, exp = 8 }, -- Sinfall Scenario
    [2362] = { ls = 3807424, exp = 8 }, -- Maldraxxus Covenant Finale Scenario
    [2363] = { ls = 3807424, exp = 8 }, -- 9.0 - Ardenweald - Garden - Queen's Cons
    [2364] = { ls = 3807424, exp = 8 }, -- The Maw
    [2365] = { exp = 8 }, -- 9.0 Maw - Torghast - 9Maw_Bridge_SmallPl
    [2366] = { exp = 8 }, -- 9.0 Maw - Torghast - 9Maw_Zone_WallTurre
    [2367] = { exp = 8 }, -- 9.0 Maw - Torghast - 9Maw_Bridge_Straigh
    [2368] = { ls = 3807424, exp = 8 }, -- Maldraxxus Broker Islands
    [2369] = { exp = 7 }, -- 9.0 NPE - Horde - Starter Transport Ship
    [2370] = { ls = 3807424, exp = 8 }, -- Maldraxxus Arena
    [2371] = { ls = 3807424, exp = 8 }, -- 9.0 Ardenweald Covenant Finale Drust Sce
    [2373] = { ls = 3622958, exp = 8 }, -- Empyrean Domain
    [2374] = { ls = 4370748, exp = 8 }, -- Zereth Mortis
    [2375] = { ls = 3622958, exp = 8 }, -- 9.0 Bastion Arena - Path of Ascension
    [2439] = { ls = 3638598, exp = 8 }, -- De Other Side (Ardenweald Campaign)
    [2441] = { ls = 4179243, exp = 8 }, -- Tazavesh, the Veiled Market
    [2444] = { ls = 4669853, exp = 9 }, -- Dragon Isles
    [2450] = { ls = 4178070, exp = 8 }, -- Sanctum of Domination
    [2451] = { ls = 4566644, exp = 9 }, -- Uldaman: Legacy of Tyr
    [2453] = { ls = 3807424, exp = 8 }, -- Torghast
    [2454] = { ls = 4669853, exp = 9 }, -- Zaralek Cavern
    [2456] = { ls = 3807424, exp = 8 }, -- The Maw
    [2464] = { ls = 3807424, exp = 8 }, -- 9.1 Battle of Ardenweald
    [2465] = { ls = 1498773, exp = 8 }, -- 9.1 Andorhal - Kyrian Chapter Scenario
    [2469] = { exp = 8 }, -- Torghast
    [2471] = { ls = 3807424, exp = 8 }, -- Torghast
    [2472] = { ls = 1454826, exp = 8 }, -- Skyhold
    [2481] = { ls = 4391868, exp = 8 }, -- Sepulcher of the First Ones
    [2482] = { ls = 3621966, exp = 8 }, -- Font of Fealty
    [2485] = { exp = 8 }, -- Torghast
    [2486] = { exp = 8 }, -- Torghast
    [2487] = { exp = 8 }, -- Torghast
    [2488] = { exp = 8 }, -- Torghast
    [2489] = { exp = 8 }, -- Torghast
    [2490] = { exp = 8 }, -- Torghast
    [2504] = { ls = 3807424, exp = 8 }, -- Path of the Primus
    [2507] = { exp = 0 }, -- Void Zone: Airship
    [2509] = { ls = 4370747, exp = 8 }, -- Maldraxxus Coliseum
    [2512] = { ls = 4669853, exp = 9 }, -- Grand Time Adventure
    [2515] = { ls = 4566643, exp = 9 }, -- The Azure Vault
    [2516] = { ls = 4684456, exp = 9 }, -- The Nokhud Offensive
    [2518] = { exp = 9 }, -- Old Beyfir
    [2519] = { ls = 4691725, exp = 9 }, -- Neltharus
    [2520] = { ls = 4697004, exp = 9 }, -- Brackenhide Hollow
    [2521] = { ls = 4550300, exp = 9 }, -- Ruby Life Pools
    [2522] = { ls = 4663453, exp = 9 }, -- Vault of the Incarnates
    [2523] = { exp = 9 }, -- The Defiant Dragonscale
    [2524] = { exp = 9 }, -- The Rugged Dragonscale
    [2526] = { ls = 4550301, exp = 9 }, -- Algeth'ar Academy
    [2527] = { ls = 4661969, exp = 9 }, -- Halls of Infusion
    [2529] = { exp = 9 }, -- Young Belvo
    [2532] = { ls = 1498773, exp = 8 }, -- Ruins of Lordaeron
    [2534] = { ls = 4669853, exp = 9 }, -- 10.0 Dragon Isles -  Black Dragon Citade
    [2547] = { ls = 4391867, exp = 8 }, -- Enigma Crucible
    [2548] = { ls = 5344997, exp = 9 }, -- Emerald Dream
    [2549] = { ls = 5409944, exp = 9 }, -- Amirdrassil, the Dream's Hope
    [2552] = { ls = 5899485, exp = 10 }, -- Khaz Algar (Surface)
    [2556] = { ls = 1476725, exp = 9 }, -- Emerald Dreamway
    [2559] = { ls = 3807424, exp = 8 }, -- Shadowlands
    [2563] = { ls = 4731628, exp = 9 }, -- Nokhudon Proving Grounds
    [2569] = { ls = 5140749, exp = 9 }, -- Aberrus, the Shadowed Crucible
    [2570] = { ls = 4669853, exp = 8 }, -- 10.0 The Forbidden Reach (Child of 2444)
    [2573] = { exp = 9 }, -- Lost Arvillo
    [2574] = { ls = 1446595, exp = 9 }, -- Dragon Isles
    [2576] = { ls = 131834, exp = 9 }, -- Sully Test Space
    [2579] = { ls = 5211661, exp = 9 }, -- Dawn of the Infinite
    [2582] = { ls = 131861, exp = 0 }, -- Alterac Valley
    [2583] = { ls = 4669853, exp = 9 }, -- Tyr's Fall Scenario
    [2586] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - Murloc (Azmerloth)
    [2587] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - Robot (A.Z.E.R.O.T.H
    [2590] = { ls = 4566643, exp = 9 }, -- The Azure Vault
    [2593] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - Black Empire (Azq'ro
    [2594] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - Argus Raid UNUSED
    [2595] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - Demon (Azewrath)
    [2597] = { ls = 4669853, exp = 9 }, -- 10.1 Zaralek Caverns - Chapter 1 Scenari
    [2598] = { ls = 4669853, exp = 0 }, -- Zaralek Caverns - Chapter 6 scenario
    [2599] = { ls = 4669853, exp = 0 }, -- Zaralek Caverns - Chapter 6 Scenario
    [2600] = { ls = 4669853, exp = 9 }, -- 10.1 Zaralek Caverns - Chapter 6 Scenari
    [2601] = { ls = 5899485, exp = 10 }, -- Khaz Algar
    [2614] = { ls = 4669853, exp = 9 }, -- [DNT] DELETE
    [2616] = { exp = 9 }, -- Zskera Vaults
    [2625] = { ls = 4669853, exp = 9 }, -- Deathwing's Final Moment
    [2634] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - HvA (The Warlands)
    [2635] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - Titan (Ulderoth)
    [2637] = { ls = 4669853, exp = 9 }, -- Dragon Isles
    [2639] = { ls = 131830, exp = 9 }, -- 10.1.5 Time Rifts - Scourge (Azmourne)
    [2644] = { ls = 1454826, exp = 9 }, -- 10.2.0 - Halls of Valor - Misfit Dragons
    [2645] = { ls = 645156, exp = 9 }, -- 10.1.5 Scarlet Monastery - Headless Hors
    [2648] = { ls = 5763550, exp = 10 }, -- The Rookery
    [2649] = { ls = 5874076, exp = 10 }, -- Priory of the Sacred Flame
    [2651] = { ls = 5794590, exp = 10 }, -- Darkflame Cleft
    [2652] = { ls = 5795799, exp = 10 }, -- The Stonevault
    [2653] = { ls = 5140749, exp = 9 }, -- 10.2 Scenario
    [2654] = { ls = 1448532, exp = 9 }, -- 10.2. Nighthold
    [2656] = { ls = 5828239, exp = 10 }, -- Deephaul Ravine
    [2657] = { ls = 5791579, exp = 10 }, -- Nerub-ar Palace
    [2660] = { ls = 5898878, exp = 10 }, -- Ara-Kara, City of Echoes
    [2661] = { ls = 5863045, exp = 10 }, -- Cinderbrew Meadery
    [2662] = { ls = 5779652, exp = 10 }, -- The Dawnbreaker
    [2664] = { ls = 5899485, exp = 10 }, -- Fungal Folly
    [2666] = { ls = 4669853, exp = 9 }, -- Amirdrassil
    [2668] = { ls = 131830, exp = 9 }, -- 10.1.7 Tyr Scenario - Black Empire
    [2669] = { ls = 5887871, exp = 10 }, -- City of Threads
    [2671] = { exp = 10 }, -- The Dawnbreaker
    [2672] = { exp = 10 }, -- The Dawnbreaker
    [2673] = { exp = 10 }, -- Ambush Airship A
    [2674] = { exp = 10 }, -- Ambush Airship B
    [2676] = { exp = 10 }, -- Ambush Airship C
    [2677] = { exp = 10 }, -- Ambush Airship D
    [2678] = { ls = 5211661, exp = 9 }, -- The Timeways (Dawn of the Infinite Outdo
    [2679] = { ls = 5899485, exp = 10 }, -- Mycomancer Cavern
    [2680] = { ls = 5899485, exp = 10 }, -- Earthcrawl Mines
    [2681] = { ls = 5899485, exp = 10 }, -- Kriegval's Rest
    [2682] = { ls = 5899485, exp = 10 }, -- Zekvir's Lair
    [2683] = { ls = 5899485, exp = 10 }, -- The Waterworks
    [2684] = { ls = 5899485, exp = 10 }, -- The Dread Pit
    [2685] = { ls = 5899485, exp = 10 }, -- Skittering Breach
    [2686] = { ls = 5899485, exp = 10 }, -- Nightfall Sanctum
    [2687] = { ls = 5899485, exp = 10 }, -- The Sinkhole
    [2688] = { ls = 5899485, exp = 10 }, -- The Spiral Weave
    [2689] = { ls = 5899485, exp = 10 }, -- Tak-Rethan Abyss
    [2690] = { ls = 5899485, exp = 10 }, -- The Underkeep
    [2692] = { ls = 5899485, exp = 10 }, -- Hall of Awakening
    [2694] = { ls = 7385003, exp = 11 }, -- Harandar
    [2695] = { ls = 5580542, exp = 8 }, -- Void Zone: Arathi Highlands
    [2698] = { ls = 5899485, exp = 0 }, -- 11.0 - Chamber of Heart
    [2699] = { ls = 5794590, exp = 10 }, -- New Candle, New Hope
    [2703] = { ls = 4669853, exp = 10 }, -- 11.0 Warband Screen
    [2704] = { ls = 4669853, exp = 10 }, -- 11.0 Warband Testing 2
    [2706] = { ls = 6392587, exp = 10 }, -- Undermine
    [2708] = { exp = 9 }, -- 10.2.5 Transport: Bel'ameth -> Gilneas
    [2710] = { ls = 5899485, exp = 10 }, -- Awakening The Machine
    [2713] = { exp = 10 }, -- 11.0 - Campaign Finale Scenario
    [2716] = { exp = 10 }, -- 11.0 - Priory Scenario
    [2728] = { exp = 10 }, -- 11.0.0 Transport: The Reckoning (Crashed
    [2731] = { ls = 5899485, exp = 10 }, -- 11.0 Dalaran Scenario
    [2735] = { ls = 7377860, exp = 10 }, -- Founder's Point
    [2736] = { ls = 7490877, exp = 10 }, -- Razorwind Shores
    [2738] = { ls = 6918681, exp = 10 }, -- K'aresh
    [2739] = { ls = 5899485, exp = 10 }, -- Hall of Awakening
    [2759] = { ls = 6647403, exp = 10 }, -- Cage of Carnage
    [2760] = { exp = 10 }, -- 11.0.0 Transport: Arathi Airship 1
    [2761] = { exp = 10 }, -- 11.0.0 Transport: Arathi Airship 2
    [2762] = { exp = 10 }, -- 11.0.0 Transport: Arathi Airship 3
    [2763] = { exp = 10 }, -- 11.0.0 Transport: Arathi Airship 4
    [2764] = { exp = 10 }, -- 11.0.0 Transport: Arathi Airship 5
    [2767] = { ls = 5899485, exp = 10 }, -- The Sinkhole
    [2768] = { ls = 5899485, exp = 10 }, -- Tak-Rethan Abyss
    [2769] = { ls = 6404488, exp = 10 }, -- Liberation of Undermine
    [2771] = { ls = 7507883, exp = 11 }, -- Voidstorm
    [2773] = { ls = 6392586, exp = 10 }, -- Operation: Floodgate
    [2774] = { ls = 5899485, exp = 10 }, -- Khaz Algar
    [2776] = { ls = 1498775, exp = 0 }, -- Kalimdor
    [2779] = { ls = 236059, exp = 10 }, -- zzzUnused
    [2780] = { exp = 10 }, -- 11.0.0 Transport: Arathi Airship 7
    [2782] = { ls = 1780110, exp = 10 }, -- 11.0 - Vault of Memory
    [2783] = { ls = 7367528, exp = 10 }, -- Home Interior
    [2785] = { ls = 4669853, exp = 9 }, -- Dragon Isles
    [2786] = { ls = 5899485, exp = 10 }, -- Pocket Dimension
    [2792] = { ls = 131824, exp = 0 }, -- Blackrock Depths
    [2794] = { ls = 1375895, exp = 6 }, -- 11.2.7 - The Wandering Isle
    [2796] = { ls = 5899485, exp = 10 }, -- Arathi Highlands 3
    [2799] = { ls = 7488402, exp = 11 }, -- Slayer's Rise
    [2801] = { ls = 3170732, exp = 0 }, -- Ny'alotha, the Waking City
    [2803] = { ls = 5899485, exp = 10 }, -- Archival Assault
    [2805] = { ls = 7266211, exp = 11 }, -- Windrunner Spire
    [2810] = { ls = 6996937, exp = 0 }, -- Manaforge Omega
    [2811] = { ls = 7439363, exp = 11 }, -- Magisters' Terrace
    [2813] = { ls = 7266209, exp = 11 }, -- Murder Row
    [2815] = { ls = 5899485, exp = 10 }, -- Excavation Site 9
    [2816] = { exp = 11 }, -- Delete me please
    [2818] = { ls = 447134, exp = 0 }, -- Lordaeron Garrison
    [2819] = { ls = 318964, exp = 10 }, -- 11.1.7 Icecrown Citadel
    [2820] = { ls = 1498773, exp = 0 }, -- Eastern Kingdoms - Copy
    [2821] = { exp = 10 }, -- Bilge Rat Corsair A
    [2822] = { exp = 10 }, -- Bilge Rat Corsair B
    [2823] = { exp = 10 }, -- Bilge Rat Corsair C
    [2825] = { ls = 7266210, exp = 11 }, -- Den of Nalorakk
    [2826] = { ls = 5899485, exp = 10 }, -- Sidestreet Sluice
    [2827] = { ls = 3195545, exp = 10 }, -- Horrific Vision of Stormwind
    [2828] = { ls = 3195545, exp = 10 }, -- Horrific Vision of Orgrimmar
    [2829] = { exp = 10 }, -- The Dauntless
    [2830] = { ls = 6921876, exp = 10 }, -- Eco-Dome Al'dani
    [2831] = { ls = 5899485, exp = 10 }, -- Demolition Dome
    [2834] = { ls = 4669853, exp = 10 }, -- 11.1 Warband - General
    [2836] = { ls = 5899485, exp = 10 }, -- Earthcrawl Mines
    [2837] = { ls = 4669853, exp = 10 }, -- 11.1 Warband - Delve Select Screen - Nig
    [2847] = { ls = 4669853, exp = 10 }, -- 11.1 Warband - Freywold
    [2849] = { ls = 6392587, exp = 10 }, -- Dastardly Dome
    [2851] = { ls = 4669853, exp = 10 }, -- 11.1 Warband - The Gallagio
    [2857] = { ls = 643908, exp = 11 }, -- Scarlet Halls
    [2858] = { ls = 7578182, exp = 11 }, -- 12.0 Quel'Danas Scenario
    [2859] = { ls = 7354407, exp = 11 }, -- The Blinding Vale
    [2860] = { exp = 11 }, -- Blood Elf Frigate (Scenario)
    [2872] = { exp = 8 }, -- Undermine
    [2874] = { ls = 7322720, exp = 11 }, -- Maisara Caverns
    [2907] = { ls = 7578182, exp = 11 }, -- 12.0 - Silvermoon City - Campaign Finale
    [2912] = { ls = 7488403, exp = 11 }, -- The Voidspire
    [2913] = { ls = 7454099, exp = 11 }, -- March on Quel'Danas
    [2915] = { ls = 7551421, exp = 11 }, -- Nexus-Point Xenas
    [2923] = { ls = 7439364, exp = 11 }, -- Voidscar Arena
    [2927] = { ls = 5899485, exp = 9 }, -- Arathi Highlands RPE
    [2928] = { exp = 11 }, -- Shadowguard Point OLD
    [2930] = { ls = 5899485, exp = 10 }, -- Midnight
    [2933] = { ls = 1498773, exp = 11 }, -- Collegiate Calamity
    [2939] = { ls = 7551422, exp = 11 }, -- The Dreamrift
    [2950] = { ls = 4663453, exp = 9 }, -- Vault of the Incarnates
    [2951] = { ls = 6918681, exp = 10 }, -- Voidrazor Sanctuary
    [2952] = { ls = 1498773, exp = 11 }, -- The Shadow Enclave
    [2953] = { ls = 1498773, exp = 11 }, -- Parhelion Plaza
    [2954] = { ls = 4669853, exp = 10 }, -- 11.2 Warband - K'aresh
    [2961] = { ls = 1498773, exp = 11 }, -- Twilight Crypts
    [2962] = { ls = 1498773, exp = 11 }, -- Atal'Aman
    [2963] = { ls = 1498773, exp = 11 }, -- The Grudge Pit
    [2964] = { ls = 1498773, exp = 11 }, -- The Gulf of Memory
    [2965] = { ls = 1498773, exp = 11 }, -- Sunkiller Sanctum
    [2966] = { ls = 1498773, exp = 11 }, -- Torment's Rise
    [2972] = { ls = 5409944, exp = 9 }, -- DEPRECATED Amirdrassil, the Dream's Hope
    [2979] = { ls = 1498773, exp = 11 }, -- Shadowguard Point
    [2982] = { exp = 11 }, -- DELETE ME
    [2984] = { exp = 0 }, -- 12.0.0 Transport: Ethereal Skiff
    [2987] = { exp = 11 }, -- Renamed
    [3003] = { ls = 1395129, exp = 11 }, -- The Darkway
    [3007] = { ls = 131830, exp = 11 }, -- The Escape from Durnholde - Lorewalking
    [3009] = { ls = 131874, exp = 0 }, -- 12.0.5 - Prop Hunt - Silvermoon
    [3014] = { ls = 7765534, exp = 11 }, -- Broken Throne
    [3019] = { ls = 7578182, exp = 11 }, -- 12.0 Quel'Danas Intro Scenario Ship Map
    [3022] = { ls = 7734005, exp = 11 }, -- Silvermoon's Falconwing Square
    [3026] = { exp = 11 }, -- 12.0 Warband - Founder's Point
    [3027] = { exp = 11 }, -- 12.0 Warband - Razorwind Shores
    [3029] = { exp = 0 }, -- Keystone Dungeons
    [3038] = { ls = 1498773, exp = 0 }, -- internalname
    [3047] = { ls = 7816621, exp = 11 }, -- Val
    [3074] = { ls = 7765536, exp = 11 }, -- Daggerspine Point
    [3075] = { ls = 7816620, exp = 11 }, -- Naigtal
}
