#!/usr/bin/env node
// tools/gen_loadingscreens.mjs — regenerate Lib/LoadingScreenData.lua from the client database.
//   node tools/gen_loadingscreens.mjs            # fetches wago.tools exports for the LIVE build
//
// WHY: there is no runtime API from a map to its loading screen -- the link lives in the client's
// Map.db2 (LoadingScreenID per map instance) and LoadingScreens.db2 (the screen's texture file ids).
// wago.tools exports both as CSV, so this script bakes them into ONE generated Lua table:
//   ns.MapLoadingScreen = { [mapID] = { ls = <fileDataID or nil>, exp = <expansionID> }, ... }
// keyed by the WORLD map instance id (what C_Map.GetWorldPosFromMapPos returns for a uiMapID).
// The Dashboard's zone catalog resolves each zone to its map id at runtime and looks the art up
// here. Regenerate after each patch (the data is static within a build).

const MAP_URL = "https://wago.tools/db2/Map/csv";
const LS_URL  = "https://wago.tools/db2/LoadingScreens/csv";

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "Lib", "LoadingScreenData.lua");

// Minimal RFC-ish CSV parser: handles quoted fields containing commas, quotes ("") and NEWLINES
// (Map.db2 descriptions are multi-line). Returns an array of rows (arrays of strings).
function parseCsv(text) {
  const rows = [];
  let row = [], field = "", inQ = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQ) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false;
      } else field += ch;
    } else if (ch === '"') inQ = true;
    else if (ch === ",") { row.push(field); field = ""; }
    else if (ch === "\n" || ch === "\r") {
      if (ch === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.length > 1 || row[0] !== "") rows.push(row);
      row = [];
    } else field += ch;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function indexHeader(rows) {
  const idx = {};
  rows[0].forEach((name, i) => { idx[name] = i; });
  return idx;
}

const [mapCsv, lsCsv] = await Promise.all([
  fetch(MAP_URL).then((r) => { if (!r.ok) throw new Error(`Map.db2 fetch: ${r.status}`); return r.text(); }),
  fetch(LS_URL).then((r) => { if (!r.ok) throw new Error(`LoadingScreens.db2 fetch: ${r.status}`); return r.text(); }),
]);

const ls = parseCsv(lsCsv);
const lsIdx = indexHeader(ls);
// best texture per screen: the 16:9 widescreen art when present, then wide, main, narrow
const lsPick = ["WideScreen169FileDataID", "WideScreenFileDataID", "MainImageFileDataID", "NarrowScreenFileDataID"]
  .map((k) => lsIdx[k]).filter((i) => i !== undefined);
const screenFile = {};
for (let r = 1; r < ls.length; r++) {
  const id = parseInt(ls[r][lsIdx.ID], 10);
  for (const col of lsPick) {
    const f = parseInt(ls[r][col], 10);
    if (f > 0) { screenFile[id] = f; break; }
  }
}

const map = parseCsv(mapCsv);
const mIdx = indexHeader(map);
const lines = [];
let withArt = 0;
for (let r = 1; r < map.length; r++) {
  const row = map[r];
  const id = parseInt(row[mIdx.ID], 10);
  if (!Number.isFinite(id)) continue;
  const exp = parseInt(row[mIdx.ExpansionID], 10) || 0;
  const file = screenFile[parseInt(row[mIdx.LoadingScreenID], 10)];
  const name = (row[mIdx.MapName_lang] || "").replace(/[\r\n].*/s, "").slice(0, 40);
  if (file) withArt++;
  lines.push(`    [${id}] = { ${file ? "ls = " + file + ", " : ""}exp = ${exp} }, -- ${name.replace(/--/g, "- -")}`);
}

const out = `local addonName, ns = ...

-- Lib/LoadingScreenData.lua
-- GENERATED by tools/gen_loadingscreens.mjs -- do not edit by hand; regenerate after a patch.
-- One entry per WORLD map instance id (Map.db2): its loading screen's texture fileDataID (ls,
-- absent when the map has no own screen) and its expansion id (exp). Resolved at runtime from a
-- zone's uiMapID via C_Map.GetWorldPosFromMapPos (see the Dashboard's zone catalog).
ns.MapLoadingScreen = {
${lines.join("\n")}
}
`;
writeFileSync(OUT, out);
console.log(`gen_loadingscreens: ${lines.length} maps (${withArt} with own loading screen) -> Lib/LoadingScreenData.lua`);
